// @ts-nocheck
// Module: state/runtime-state -- authoritative mutable mode state singleton.

// -------------------- Authoritative State Map --------------------
//
// Flow state (resets at mode setup):
// - State.round.phase: MatchPhase.NotReady | MatchPhase.Live | MatchPhase.GameOver.
// - State.round.clock.durationSeconds: authoritative remaining seconds in the live-phase timer.
// - State.round.clock.matchLengthSeconds: configured starting duration for each live start.
//
// Match state (resets at match start):
// - State.match.isEnded: indicates match is over and victory dialog should be shown.
//
// Vehicle registration (persists across live-flow transitions unless explicitly cleared):
// - regVehiclesTeam1 (GlobalVariable 0): array of vehicles registered to Team 1.
// - regVehiclesTeam2 (GlobalVariable 1): array of vehicles registered to Team 2.
// - vehIds/vehOwners: best-effort 'last driver' mapping used for messages only.
//
// UI caches (per-player, rebuilt as needed):
// - State.hudCache.hudByPid[pid]: cached HUD widget references.
// - State.hudCache.topHudShellByPid[pid]: cached non-combat top-HUD shell references.
// - dialog/widget caches: cached references to modal UI elements (ready dialog, victory, clock digits).
//
// ------------------------------------------------------------------

// Centralized mutable state for mode flow and UI caches.
const State: GameState = {
    round: {
        autoStartMinActivePlayers: DEFAULT_AUTO_START_MIN_ACTIVE_PLAYERS,
        matchupPresetIndex: DEFAULT_MATCHUP_PRESET_INDEX,
        lastMatchupChangeAtSeconds: -999,
        modeConfig: {
            gameModeIndex: READY_DIALOG_GAME_MODE_DEFAULT_INDEX,
            aircraftCeiling: READY_DIALOG_AIRCRAFT_CEILING_DEFAULT,
            aircraftCeilingOverridePending: false,
            vehicleIndexT1: READY_DIALOG_VEHICLE_T1_DEFAULT_INDEX,
            vehicleIndexT2: READY_DIALOG_VEHICLE_T2_DEFAULT_INDEX,
            gameMode: READY_DIALOG_GAME_MODE_OPTIONS[READY_DIALOG_GAME_MODE_DEFAULT_INDEX],
            gameSettings: mod.stringkeys.twl.readyDialog.modeSettingAircraftCeilingFormat,
            vehiclesT1: READY_DIALOG_VEHICLE_OPTIONS[READY_DIALOG_VEHICLE_T1_DEFAULT_INDEX],
            vehiclesT2: READY_DIALOG_VEHICLE_OPTIONS[READY_DIALOG_VEHICLE_T2_DEFAULT_INDEX],
            confirmed: {
                gameMode: READY_DIALOG_GAME_MODE_OPTIONS[READY_DIALOG_GAME_MODE_DEFAULT_INDEX],
                gameSettings: mod.stringkeys.twl.readyDialog.modeSettingAircraftCeilingFormat,
                vehiclesT1: READY_DIALOG_VEHICLE_OPTIONS[READY_DIALOG_VEHICLE_T1_DEFAULT_INDEX],
                vehiclesT2: READY_DIALOG_VEHICLE_OPTIONS[READY_DIALOG_VEHICLE_T2_DEFAULT_INDEX],
                aircraftCeiling: READY_DIALOG_AIRCRAFT_CEILING_DEFAULT,
                aircraftCeilingOverrideEnabled: false,
                vehicleIndexT1: READY_DIALOG_VEHICLE_T1_DEFAULT_INDEX,
                vehicleIndexT2: READY_DIALOG_VEHICLE_T2_DEFAULT_INDEX,
                vehicleOverrideEnabled: false,
            },
        },
        phase: MatchPhase.NotReady,
        clock: {
            durationSeconds: ROUND_CLOCK_DEFAULT_SECONDS,
            matchLengthSeconds: ROUND_CLOCK_DEFAULT_SECONDS,
            matchStartElapsedSeconds: undefined,
            pausedRemainingSeconds: undefined,
            isPaused: false,
            lastDisplayedSeconds: undefined,
            lastLowTimeState: undefined,
            expiryFired: false,
            expiryHandlers: [],
        },
        flow: {
            cleanupActive: false,
            cleanupAllowDeploy: false,
        },
        countdown: {
            isActive: false,
            isRequested: false,
            token: 0,
        },
        aircraftCeiling: {
            mapDefaultHudCeiling: READY_DIALOG_AIRCRAFT_CEILING_DEFAULT,
            hudMaxY: READY_DIALOG_AIRCRAFT_CEILING_DEFAULT,
            hudFloorY: 0,
            customEnabled: false,
            enforcementToken: 0,
            vehicleStates: {},
        },
    },
    conquest: {
        lifecyclePhase: "NOT_READY",
        tickets: {
            team1: CONQUEST_STARTING_TICKETS,
            team2: CONQUEST_STARTING_TICKETS,
        },
        bleed: {
            enabled: true,
            lastTickSeconds: -1,
            perDiffPerSecond: CONQUEST_BLEED_PER_DIFF_PER_SECOND,
            carryTeam1: 0,
            carryTeam2: 0,
        },
        capture: {
            byObjId: {},
            mappedObjIdsInOrder: [],
            lastUnmappedObjId: undefined,
            unmappedSeenCount: 0,
            visualByObjId: {},
            engagedObjIdByPid: {},
        },
        sound: {
            enabled: true,
            captureTickFriendlyHandle: undefined,
            captureTickEnemyHandle: undefined,
            handlesReady: false,
            queue: [],
            lastFlushAtSeconds: -1,
            lastEventAtByThrottleKey: {},
            debug: {
                queuedCount: 0,
                coalescedCount: 0,
                dispatchedCount: 0,
                dispatchedFriendlyCount: 0,
                dispatchedEnemyCount: 0,
                suppressedCount: 0,
                suppressedThrottleCount: 0,
                droppedNoHandleCount: 0,
                droppedNoRecipientCount: 0,
                droppedInvalidEventCount: 0,
                spawnFailureCount: 0,
                lastQueueDepth: 0,
                maxQueueDepth: 0,
                lastRecipientCount: 0,
                lastFlushQueuedCount: 0,
                lastFlushDispatchedCount: 0,
                lastFlushSuppressedCount: 0,
                lastFlushDroppedCount: 0,
                lastEventObjId: 0,
                lastEventSourceTeamId: 0,
                lastEventQueuedAtSeconds: -1,
                lastDispatchedAtSeconds: -1,
                playerCleanupCount: 0,
                lastCleanupPid: 0,
            },
        },
        vo: {
            enabled: true,
            runtimeHandleByPid: {},
            handlesReadyByPid: {},
            queue: [],
            lastFlushAtSeconds: -1,
            lastEventAtByThrottleKey: {},
            objectiveStateByObjId: {},
            recentActiveObjIdByPid: {},
            recentActiveAtSecondsByPid: {},
            debug: {
                queuedCount: 0,
                coalescedCount: 0,
                dispatchedCount: 0,
                suppressedCount: 0,
                droppedNoHandleCount: 0,
                droppedNoRecipientCount: 0,
                droppedInvalidEventCount: 0,
                droppedNoFlagCount: 0,
                spawnFailureCount: 0,
                lastQueueDepth: 0,
                maxQueueDepth: 0,
                lastRecipientCount: 0,
                lastFlushQueuedCount: 0,
                lastFlushDispatchedCount: 0,
                lastFlushSuppressedCount: 0,
                lastFlushDroppedCount: 0,
                lastEventKey: "none",
                lastEventObjId: 0,
                lastEventSourceTeamId: 0,
                lastEventQueuedAtSeconds: -1,
                lastDispatchedAtSeconds: -1,
                playerCleanupCount: 0,
                lastCleanupPid: 0,
            },
        },
        spawnCharge: {
            enabled: false,
            chargePerDeploy: CONQUEST_SPAWN_CHARGE_PER_DEPLOY,
            firstLiveSpawnExemptByPid: {},
            deployTxnByPid: {},
            pendingReasonByPid: {},
            deployCountByReason: {
                deploy: 0,
                forced_redeploy: 0,
                team_switch: 0,
                admin_move: 0,
                phase_transition: 0,
                reconnect: 0,
            },
            chargedCountByReason: {
                deploy: 0,
                forced_redeploy: 0,
                team_switch: 0,
                admin_move: 0,
                phase_transition: 0,
                reconnect: 0,
            },
            duplicateChargeSuspicionCount: 0,
            sessionIdentityResetCount: 0,
            reconnectContinuityDropCount: 0,
            lastDebugEmitAtSeconds: -1,
        },
        endRace: {
            endLatched: false,
            endReason: undefined,
            endSnapshot: undefined,
        },
        debug: {
            hudEnabled: true,
            hudModeOverride: undefined,
            hudLastUpdatedAtSeconds: -1,
            hudDirty: true,
            ticketLeaderTeam: 0,
            hudGenerationByPid: {},
            teamSwapRefreshTokenByPid: {},
            teamSwapHudResetPendingByPid: {},
            perspectiveTeamByPid: {},
            teamSwapPerspectiveLockUntilByPid: {},
            engageHiddenUntilDeployByPid: {},
            bleedPulseQueueLeftByPid: {},
            bleedPulseQueueRightByPid: {},
            bleedPulseActiveSideByPid: {},
            bleedPulseStepByPid: {},
            bleedPulseLimitByPid: {},
            bleedPulsePhaseByPid: {},
            bleedPulseNextAtByPid: {},
            hudRenderBucketByPid: {},
            hudRenderBurstByPid: {},
            hudRenderDuplicateBurstByPid: {},
            hudStatusVmByPid: {},
            hudHelpReadyVmByPid: {},
            hudClockVmByPid: {},
            hudProjectionEngagedObjIdByPid: {},
            hudProjectionPopoutVisibleByPid: {},
            hudProjectionPopoutObjIdByPid: {},
            hudProjectionEngageVisibleByPid: {},
            hudProjectionActiveTopSlotNeutralizedByPid: {},
            hudProjectionActiveTopSlotBorderVisibleByPid: {},
            hudProjectionSwapPendingByPid: {},
            hudProjectionDeployedByPid: {},
            hudProjectionTransitionCountByPid: {},
            hudProjectionLastChangedAtByPid: {},
        },
    },
    match: {
        isEnded: false,
        victoryDialogActive: false,
        winnerTeam: undefined,
        endElapsedSecondsSnapshot: 0,
        victoryStartElapsedSecondsSnapshot: 0,
        flow: {
            matchEndDelayToken: 0,
        },
    },
    admin: {
        actionCount: 0,
        debugLoopActive: false,
    },
    debug: {
        highlightedMessageCount: 0,
        lastHighlightedMessageAtSeconds: -1,
        lastHighlightedMessageKey: -1,
    },
    players: {
        readyDialogData: {},
        readyByPid: {},
        readyMessageCooldownByPid: {},
        joinPromptShownByPid: {},
        joinPromptNeverShowByPidMap: {},
        joinPromptReadyDialogOpenedByPid: {},
        joinPromptTipIndexByPid: {},
        joinPromptTipsUnlockedByPid: {},
        joinPromptTripleTapArmedByPid: {},
        joinPromptPolicyDisabledByPid: {},
        joinPromptPolicySuppressedCountByPid: {},
        joinPromptLastPolicySuppressedAtSecondsByPid: {},
        joinPromptLastSuppressionReasonByPid: {},
        inMainBaseByPid: {},
        overTakeoffLimitByPid: {},
        deployedByPid: {},
        disconnectedByPid: {},
        uiInputEnabledByPid: {},
        posDebugTransformSourceByPid: {},
        posDebugVehicleObjIdByPid: {},
    },
    vehicles: {
        slots: [],
        vehicleToSlot: {},
        desiredEnabledSlotsTeam1: 0,
        desiredEnabledSlotsTeam2: 0,
        spawnSequenceToken: 0,
        spawnSequenceInProgress: false,
        activeSpawnSlotIndex: undefined,
        activeSpawnToken: undefined,
        activeSpawnRequestedAtSeconds: undefined,
        configReady: false,
        startupCleanupDone: false,
    },
    hudCache: {
        hudByPid: {},
        topHudShellByPid: {},
        clockWidgetCache: {},
        countdownWidgetCache: {},
        vehicleDeployTimerCache: {},
    },
};
