// @ts-nocheck
// Module: state/runtime-state -- authoritative mutable mode state singleton.

// Centralized mutable state for mode flow and UI caches.
const State: GameState = {
    round: {
        autoStartMinActivePlayers: DEFAULT_AUTO_START_MIN_ACTIVE_PLAYERS,
        matchupPresetIndex: DEFAULT_MATCHUP_PRESET_INDEX,
        lastMatchupChangeAtSeconds: -999,
        modeConfig: {
            gameModeIndex: READY_DIALOG_GAME_MODE_DEFAULT_INDEX,
            autoStartMinActivePlayers: DEFAULT_AUTO_START_MIN_ACTIVE_PLAYERS,
            aircraftCeiling: READY_DIALOG_AIRCRAFT_CEILING_DEFAULT,
            aircraftCeilingOverridePending: false,
            vehicleSelectionIndexByKey: {},
            gameMode: READY_DIALOG_GAME_MODE_OPTIONS[READY_DIALOG_GAME_MODE_DEFAULT_INDEX],
            gameSettings: mod.stringkeys.twl.readyDialog.modeSettingAircraftCeilingFormat,
            vehicleDeployMethod: VEHICLE_DEPLOY_METHOD_DEFAULT,
            confirmed: {
                gameMode: READY_DIALOG_GAME_MODE_OPTIONS[READY_DIALOG_GAME_MODE_DEFAULT_INDEX],
                gameSettings: mod.stringkeys.twl.readyDialog.modeSettingAircraftCeilingFormat,
                aircraftCeiling: READY_DIALOG_AIRCRAFT_CEILING_DEFAULT,
                aircraftCeilingOverrideEnabled: false,
                autoStartMinActivePlayers: DEFAULT_AUTO_START_MIN_ACTIVE_PLAYERS,
                vehicleSelectionIndexByKey: {},
                vehicleDeployMethod: VEHICLE_DEPLOY_METHOD_DEFAULT,
            },
        },
        phase: MatchPhase.NotReady,
        clock: {
            durationSeconds: ROUND_CLOCK_DEFAULT_SECONDS,
            matchLengthSeconds: ROUND_CLOCK_DEFAULT_SECONDS,
            matchStartElapsedSeconds: undefined,
            pausedRemainingSeconds: undefined,
            isPaused: false,
            lastDisplayedSeconds: undefined,
            lastLowTimeState: undefined,
            expiryFired: false,
            expiryHandlers: [],
        },
        flow: {
            cleanupActive: false,
            cleanupAllowDeploy: false,
        },
        liveStartedAtSeconds: undefined as number | undefined,
        countdown: {
            isActive: false,
            isRequested: false,
            token: 0,
        },
        aircraftCeiling: {
            mapDefaultHudCeiling: READY_DIALOG_AIRCRAFT_CEILING_DEFAULT,
            hudMaxY: READY_DIALOG_AIRCRAFT_CEILING_DEFAULT,
            hudFloorY: 0,
            customEnabled: false,
            enforcementToken: 0,
            vehicleStates: {},
        },
        boundary: {
            inEnemyMainBaseCoreByPid: {},
            inEnemyMainBaseBufferByPid: {},
            inGroundCombatZoneByPid: {},
            activeViolationByPid: {},
            alarmHandle: undefined,
            alarmReady: false,
            validationWarnings: [],
            nextEnforcementToken: 0,
        },
        armSfx: {
            handle: undefined,
            ready: false,
        },
        smk: {},
        asg: {},
    },
    conquest: {
        lifecyclePhase: "NOT_READY",
        tickets: {
            team1: CONQUEST_STARTING_TICKETS,
            team2: CONQUEST_STARTING_TICKETS,
        },
        bleed: {
            enabled: true,
            lastTickSeconds: -1,
            perDiffPerSecond: CONQUEST_BLEED_PER_DIFF_PER_SECOND,
            carryTeam1: 0,
            carryTeam2: 0,
        },
        capture: {
            byObjId: {},
            mappedObjIdsInOrder: [],
            lastUnmappedObjId: undefined,
            unmappedSeenCount: 0,
            visualByObjId: {},
            engagedObjIdByPid: {},
        },
        worldInteractableIconByTeamByObjId: {},
        worldInteractableVfxHandleByObjId: {},
        worldInteractableVfxLastRefreshAtSeconds: 0,
        sound: {
            enabled: true,
            captureTickFriendlyHandle: undefined,
            captureTickEnemyHandle: undefined,
            handlesReady: false,
            queue: [],
            lastFlushAtSeconds: -1,
            lastEventAtByThrottleKey: {},
        },
        vo: {
            enabled: true,
            runtimeHandleByPid: {},
            handlesReadyByPid: {},
            queue: [],
            lastFlushAtSeconds: -1,
            lastEventAtByThrottleKey: {},
            objectiveStateByObjId: {},
            recentActiveObjIdByPid: {},
            recentActiveAtSecondsByPid: {},
        },
        spawnCharge: {
            enabled: false,
            chargePerDeploy: CONQUEST_SPAWN_CHARGE_PER_DEPLOY,
            firstLiveSpawnExemptByPid: {},
            deployTxnByPid: {},
            pendingReasonByPid: {},
            deployCountByReason: {
                deploy: 0,
                forced_redeploy: 0,
                team_switch: 0,
                admin_move: 0,
                phase_transition: 0,
                reconnect: 0,
            },
            chargedCountByReason: {
                deploy: 0,
                forced_redeploy: 0,
                team_switch: 0,
                admin_move: 0,
                phase_transition: 0,
                reconnect: 0,
            },
            duplicateChargeSuspicionCount: 0,
            sessionIdentityResetCount: 0,
            reconnectContinuityDropCount: 0,
            lastDebugEmitAtSeconds: -1,
        },
        endRace: {
            endLatched: false,
            endReason: undefined,
            endSnapshot: undefined,
        },
        debug: {
            hudEnabled: true,
            hudModeOverride: undefined,
            hudLastUpdatedAtSeconds: -1,
            hudDirty: true,
            pregameReadyHudDirty: false,
            pregameDialogDirty: false,
            pregameHelpDirty: false,
            ticketLeaderTeam: 0,
            hudGenerationByPid: {},
            combatHudGenerationByPid: {},
            teamSwapRefreshTokenByPid: {},
            teamSwapHudResetPendingByPid: {},
            perspectiveTeamByPid: {},
            teamSwapPerspectiveLockUntilByPid: {},
            engageHiddenUntilDeployByPid: {},
            hudStatusVmByPid: {},
            hudHelpReadyVmByPid: {},
            hudClockVmByPid: {},
        },
    },
    match: {
        isEnded: false,
        victoryDialogActive: false,
        winnerTeam: undefined,
        endElapsedSecondsSnapshot: 0,
        victoryStartElapsedSecondsSnapshot: 0,
        flow: {
            matchEndDelayToken: 0,
        },
    },
    admin: {
        actionCount: 0,
        debugLoopActive: false,
        perfDiagEnabled: false,
        perfDiagTickCount: 0,
        perfDiagWindowStart: -1,
        perfDiagLastTickRate: 30,
        perfDiagLastEmitAt: -1,
        perfDiagSpikeTotal: 0,
        perfDiagMinTickRate: 999,
        perfDiagSectionMax: [],
        perfDiagSectionHits: [],
    },
    players: {
        readyDialogData: {},
        readyByPid: {},
        readyNeedsReconfirmByPid: {},
        readyMessageCooldownByPid: {},
        inMainBaseByPid: {},
        worldInteractableIconByPidByObjId: {},
        armO: {},
        armI: {},
        armT: {},
        armG: {},
        armL: {},
        armS: {},
        uiCachePerfByPid: {},
        deployedByPid: {},
        disconnectedByPid: {},
        uiInputEnabledByPid: {},
        liveVehicleDeployMenuVisibleByPid: {},
        posDebugTransformSourceByPid: {},
        posDebugVehicleObjIdByPid: {},
        kpiByPid: {},
    },
    vehicles: {
        slots: [],
        vehicleToSlot: {},
        desiredEnabledSlotsTeam1: 0,
        desiredEnabledSlotsTeam2: 0,
        spawnSequenceToken: 0,
        spawnSequenceInProgress: false,
        activeSpawnSlotIndex: undefined,
        activeSpawnToken: undefined,
        activeSpawnRequestedAtSeconds: undefined,
        configReady: false,
        startupCleanupDone: false,
    },
    hudCache: {
        topHudShellByPid: {},
        clockWidgetCache: {},
        countdownWidgetCache: {},
        vehicleDeployTimerCache: {},
        ammoResupplyMenuCache: {},
        boundaryPromptCache: {},
    },
};

