// @ts-nocheck
// Module: hud/build-victory-dialog -- victory dialog construction for per-player HUD cache.

function buildVictoryDialogWidgets(player: mod.Player, pid: number, refs: HudRefs): void {
    const modal = modlib.ParseUI({
        name: `VictoryDialogRoot_${pid}`,
        type: "Container",
        playerId: player,
        position: [0, 135],
        size: [VICTORY_DIALOG_WIDTH, VICTORY_DIALOG_HEIGHT],
        anchor: mod.UIAnchor.Center,
        visible: false,
        padding: 0,
        bgColor: [VICTORY_BG_RGB[0], VICTORY_BG_RGB[1], VICTORY_BG_RGB[2]],
        bgAlpha: 0.95,
        bgFill: mod.UIBgFill.Solid,
        children: [
            {
                name: `VictoryDialog_Header1_${pid}`,
                type: "Text",
                position: [0, 14],
                size: [340, 22],
                anchor: mod.UIAnchor.TopCenter,
                visible: true,
                padding: 0,
                bgAlpha: 0,
                bgFill: mod.UIBgFill.None,
                textLabel: mod.stringkeys.twl.hud.branding.title,
                textColor: [1, 1, 1],
                textAlpha: 1,
                textSize: 18,
                textAnchor: mod.UIAnchor.Center,
            },
            {
                name: `VictoryDialog_Header2_${pid}`,
                type: "Text",
                position: [0, 36],
                size: [340, 22],
                anchor: mod.UIAnchor.TopCenter,
                visible: true,
                padding: 0,
                bgAlpha: 0,
                bgFill: mod.UIBgFill.None,
                textLabel: mod.stringkeys.twl.hud.branding.subtitle,
                textColor: [1, 1, 1],
                textAlpha: 1,
                textSize: 18,
                textAnchor: mod.UIAnchor.Center,
            },
            {
                name: `VictoryDialog_Screenshot_${pid}`,
                type: "Text",
                position: [0, 62],
                size: [340, 16],
                anchor: mod.UIAnchor.TopCenter,
                visible: true,
                padding: 0,
                bgAlpha: 0,
                bgFill: mod.UIBgFill.None,
                textLabel: mod.stringkeys.twl.victory.screenshotPrompt,
                textColor: [1, 1, 0],
                textAlpha: 1,
                textSize: 12,
                textAnchor: mod.UIAnchor.Center,
            },
            {
                name: `VictoryDialog_Restart_${pid}`,
                type: "Text",
                position: [0, 82],
                size: [340, 16],
                anchor: mod.UIAnchor.TopCenter,
                visible: true,
                padding: 0,
                bgAlpha: 0,
                bgFill: mod.UIBgFill.None,
                textLabel: mod.Message(mod.stringkeys.twl.victory.restartInFormat, MATCH_END_DELAY_SECONDS),
                textColor: [1, 1, 1],
                textAlpha: 1,
                textSize: 12,
                textAnchor: mod.UIAnchor.Center,
            },
            {
                name: `VictoryDialog_TotalTimeRow_${pid}`,
                type: "Container",
                position: [0, 102],
                size: [340, 16],
                anchor: mod.UIAnchor.TopCenter,
                visible: true,
                padding: 0,
                bgAlpha: 0,
                bgFill: mod.UIBgFill.None,
                children: [
                    {
                        name: `VictoryDialog_TotalTimeLabel_${pid}`,
                        type: "Text",
                        position: [-45, 0],
                        size: [130, 16],
                        anchor: mod.UIAnchor.Center,
                        visible: true,
                        padding: 0,
                        bgAlpha: 0,
                        bgFill: mod.UIBgFill.None,
                        textLabel: mod.stringkeys.twl.victory.totalMatchTimeLabel,
                        textColor: [1, 1, 1],
                        textAlpha: 1,
                        textSize: 12,
                        textAnchor: mod.UIAnchor.Center,
                    },
                    {
                        name: `VictoryDialog_TotalTimeDigits_${pid}`,
                        type: "Container",
                        position: [55, 0],
                        size: [120, 16],
                        anchor: mod.UIAnchor.Center,
                        visible: true,
                        padding: 0,
                        bgAlpha: 0,
                        bgFill: mod.UIBgFill.None,
                        children: [
                            {
                                name: `VictoryDialog_TimeHT_${pid}`,
                                type: "Text",
                                position: [-45, 0],
                                size: [10, 16],
                                anchor: mod.UIAnchor.Center,
                                visible: true,
                                padding: 0,
                                bgAlpha: 0,
                                bgFill: mod.UIBgFill.None,
                                textLabel: mod.Message(mod.stringkeys.twl.hud.clock.digit, 0),
                                textColor: [1, 1, 1],
                                textAlpha: 1,
                                textSize: 12,
                                textAnchor: mod.UIAnchor.Center,
                            },
                            {
                                name: `VictoryDialog_TimeHO_${pid}`,
                                type: "Text",
                                position: [-35, 0],
                                size: [10, 16],
                                anchor: mod.UIAnchor.Center,
                                visible: true,
                                padding: 0,
                                bgAlpha: 0,
                                bgFill: mod.UIBgFill.None,
                                textLabel: mod.Message(mod.stringkeys.twl.hud.clock.digit, 0),
                                textColor: [1, 1, 1],
                                textAlpha: 1,
                                textSize: 12,
                                textAnchor: mod.UIAnchor.Center,
                            },
                            {
                                name: `VictoryDialog_TimeC1_${pid}`,
                                type: "Text",
                                position: [-25, 0],
                                size: [10, 16],
                                anchor: mod.UIAnchor.Center,
                                visible: true,
                                padding: 0,
                                bgAlpha: 0,
                                bgFill: mod.UIBgFill.None,
                                textLabel: mod.Message(mod.stringkeys.twl.hud.clock.colon),
                                textColor: [1, 1, 1],
                                textAlpha: 1,
                                textSize: 12,
                                textAnchor: mod.UIAnchor.Center,
                            },
                            {
                                name: `VictoryDialog_TimeMT_${pid}`,
                                type: "Text",
                                position: [-15, 0],
                                size: [10, 16],
                                anchor: mod.UIAnchor.Center,
                                visible: true,
                                padding: 0,
                                bgAlpha: 0,
                                bgFill: mod.UIBgFill.None,
                                textLabel: mod.Message(mod.stringkeys.twl.hud.clock.digit, 0),
                                textColor: [1, 1, 1],
                                textAlpha: 1,
                                textSize: 12,
                                textAnchor: mod.UIAnchor.Center,
                            },
                            {
                                name: `VictoryDialog_TimeMO_${pid}`,
                                type: "Text",
                                position: [-5, 0],
                                size: [10, 16],
                                anchor: mod.UIAnchor.Center,
                                visible: true,
                                padding: 0,
                                bgAlpha: 0,
                                bgFill: mod.UIBgFill.None,
                                textLabel: mod.Message(mod.stringkeys.twl.hud.clock.digit, 0),
                                textColor: [1, 1, 1],
                                textAlpha: 1,
                                textSize: 12,
                                textAnchor: mod.UIAnchor.Center,
                            },
                            {
                                name: `VictoryDialog_TimeC2_${pid}`,
                                type: "Text",
                                position: [5, 0],
                                size: [10, 16],
                                anchor: mod.UIAnchor.Center,
                                visible: true,
                                padding: 0,
                                bgAlpha: 0,
                                bgFill: mod.UIBgFill.None,
                                textLabel: mod.Message(mod.stringkeys.twl.hud.clock.colon),
                                textColor: [1, 1, 1],
                                textAlpha: 1,
                                textSize: 12,
                                textAnchor: mod.UIAnchor.Center,
                            },
                            {
                                name: `VictoryDialog_TimeST_${pid}`,
                                type: "Text",
                                position: [15, 0],
                                size: [10, 16],
                                anchor: mod.UIAnchor.Center,
                                visible: true,
                                padding: 0,
                                bgAlpha: 0,
                                bgFill: mod.UIBgFill.None,
                                textLabel: mod.Message(mod.stringkeys.twl.hud.clock.digit, 0),
                                textColor: [1, 1, 1],
                                textAlpha: 1,
                                textSize: 12,
                                textAnchor: mod.UIAnchor.Center,
                            },
                            {
                                name: `VictoryDialog_TimeSO_${pid}`,
                                type: "Text",
                                position: [25, 0],
                                size: [10, 16],
                                anchor: mod.UIAnchor.Center,
                                visible: true,
                                padding: 0,
                                bgAlpha: 0,
                                bgFill: mod.UIBgFill.None,
                                textLabel: mod.Message(mod.stringkeys.twl.hud.clock.digit, 0),
                                textColor: [1, 1, 1],
                                textAlpha: 1,
                                textSize: 12,
                                textAnchor: mod.UIAnchor.Center,
                            },
                        ],
                    },
                ],
            },
            {
                name: `VictoryDialog_AdminActions_${pid}`,
                type: "Text",
                position: [0, 122],
                size: [340, 16],
                anchor: mod.UIAnchor.TopCenter,
                visible: false,
                padding: 0,
                bgAlpha: 0,
                bgFill: mod.UIBgFill.None,
                textLabel: mod.Message(mod.stringkeys.twl.adminPanel.actionCountVictoryFormat, 0),
                textColor: [1, 1, 0],
                textAlpha: 1,
                textSize: 12,
                textAnchor: mod.UIAnchor.Center,
            },
            {
                name: `VictoryDialog_RosterRow_${pid}`,
                type: "Container",
                position: [0, VICTORY_DIALOG_ROSTER_ROW_Y],
                size: [VICTORY_DIALOG_ROSTER_ROW_WIDTH, VICTORY_DIALOG_ROSTER_ROW_HEIGHT_MAX],
                anchor: mod.UIAnchor.TopCenter,
                visible: true,
                padding: 0,
                bgAlpha: 0,
                bgFill: mod.UIBgFill.None,
                children: [
                    {
                        name: `VictoryDialog_RosterLeft_${pid}`,
                        type: "Container",
                        position: [-85, 0],
                        size: [VICTORY_DIALOG_ROSTER_CONTAINER_WIDTH, VICTORY_DIALOG_ROSTER_ROW_HEIGHT_MAX],
                        anchor: mod.UIAnchor.TopCenter,
                        visible: true,
                        padding: 0,
                        bgColor: [VICTORY_TEAM1_BG_RGB[0], VICTORY_TEAM1_BG_RGB[1], VICTORY_TEAM1_BG_RGB[2]],
                        bgAlpha: 0.95,
                        bgFill: mod.UIBgFill.Solid,
                        children: (function () {
                            const rows: any[] = [];
                            for (let i = 0; i < TEAM_ROSTER_MAX_ROWS; i++) {
                                rows.push({
                                    name: `VictoryDialog_LeftRoster_${pid}_${i}`,
                                    type: "Text",
                                    position: [0, VICTORY_DIALOG_ROSTER_ROW_PADDING_TOP + i * VICTORY_DIALOG_ROSTER_ROW_HEIGHT],
                                    size: [VICTORY_DIALOG_ROSTER_CONTAINER_WIDTH, VICTORY_DIALOG_ROSTER_ROW_HEIGHT],
                                    anchor: mod.UIAnchor.TopCenter,
                                    visible: true,
                                    padding: 0,
                                    bgAlpha: 0,
                                    bgFill: mod.UIBgFill.None,
                                    textLabel: mod.Message(mod.stringkeys.twl.system.genericCounter, ""),
                                    textColor: [VICTORY_TEAM1_TEXT_RGB[0], VICTORY_TEAM1_TEXT_RGB[1], VICTORY_TEAM1_TEXT_RGB[2]],
                                    textAlpha: 1,
                                    textSize: 11,
                                    textAnchor: mod.UIAnchor.Center,
                                });
                            }
                            return rows;
                        })(),
                    },
                    {
                        name: `VictoryDialog_RosterRight_${pid}`,
                        type: "Container",
                        position: [85, 0],
                        size: [VICTORY_DIALOG_ROSTER_CONTAINER_WIDTH, VICTORY_DIALOG_ROSTER_ROW_HEIGHT_MAX],
                        anchor: mod.UIAnchor.TopCenter,
                        visible: true,
                        padding: 0,
                        bgColor: [VICTORY_TEAM2_BG_RGB[0], VICTORY_TEAM2_BG_RGB[1], VICTORY_TEAM2_BG_RGB[2]],
                        bgAlpha: 0.95,
                        bgFill: mod.UIBgFill.Solid,
                        children: (function () {
                            const rows: any[] = [];
                            for (let i = 0; i < TEAM_ROSTER_MAX_ROWS; i++) {
                                rows.push({
                                    name: `VictoryDialog_RightRoster_${pid}_${i}`,
                                    type: "Text",
                                    position: [0, VICTORY_DIALOG_ROSTER_ROW_PADDING_TOP + i * VICTORY_DIALOG_ROSTER_ROW_HEIGHT],
                                    size: [VICTORY_DIALOG_ROSTER_CONTAINER_WIDTH, VICTORY_DIALOG_ROSTER_ROW_HEIGHT],
                                    anchor: mod.UIAnchor.TopCenter,
                                    visible: true,
                                    padding: 0,
                                    bgAlpha: 0,
                                    bgFill: mod.UIBgFill.None,
                                    textLabel: mod.Message(mod.stringkeys.twl.system.genericCounter, ""),
                                    textColor: [VICTORY_TEAM2_TEXT_RGB[0], VICTORY_TEAM2_TEXT_RGB[1], VICTORY_TEAM2_TEXT_RGB[2]],
                                    textAlpha: 1,
                                    textSize: 11,
                                    textAnchor: mod.UIAnchor.Center,
                                });
                            }
                            return rows;
                        })(),
                    },
                ],
            },
        ],
    });

    if (modal) refs.roots.push(modal);

    refs.victoryRoot = safeFind(`VictoryDialogRoot_${pid}`);
    refs.victoryRestartText = safeFind(`VictoryDialog_Restart_${pid}`);

    refs.victoryTimeHoursTens = safeFind(`VictoryDialog_TimeHT_${pid}`);
    refs.victoryTimeHoursOnes = safeFind(`VictoryDialog_TimeHO_${pid}`);
    refs.victoryTimeMinutesTens = safeFind(`VictoryDialog_TimeMT_${pid}`);
    refs.victoryTimeMinutesOnes = safeFind(`VictoryDialog_TimeMO_${pid}`);
    refs.victoryTimeSecondsTens = safeFind(`VictoryDialog_TimeST_${pid}`);
    refs.victoryTimeSecondsOnes = safeFind(`VictoryDialog_TimeSO_${pid}`);

    refs.victoryAdminActionsText = safeFind(`VictoryDialog_AdminActions_${pid}`);
    refs.victoryRosterRow = safeFind(`VictoryDialog_RosterRow_${pid}`);
    refs.victoryRosterLeftContainer = safeFind(`VictoryDialog_RosterLeft_${pid}`);
    refs.victoryRosterRightContainer = safeFind(`VictoryDialog_RosterRight_${pid}`);

    refs.victoryLeftRosterText = [];
    refs.victoryRightRosterText = [];
    for (let i = 0; i < TEAM_ROSTER_MAX_ROWS; i++) {
        refs.victoryLeftRosterText.push(safeFind(`VictoryDialog_LeftRoster_${pid}_${i}`));
        refs.victoryRightRosterText.push(safeFind(`VictoryDialog_RightRoster_${pid}_${i}`));
    }
}
