// @ts-nocheck
// Module: compact runtime changelog

//#region -------------------- Changelog / History --------------------

// v0.649: Plan H-P0 follow-on -- add coarse-step buttons to the Vehicle Health Multiplier knob. New "-10" / "+10" buttons sit OUTSIDE the existing "<" / ">" buttons (one on each side), so the dialog row reads visually: [-10] [<] Health:NNN% [>] [+10] then a gap, then Mode Settings. Step size 0.10 multiplier = 10% per click (vs the inner 0.01 = 1%). Wider 32px buttons (vs 26px for the inner < />) with textSize 13 to fit the 3-char label. Two new strings (twl.ui.minus10 = "-10", twl.ui.plus10 = "+10") added per the same approval as v0.648. Two new event-router cases in team-switch.ts route to setReadyDialogVehicleHealthMultiplier with the coarse step. No other behavior change: still confirm-only, still applies to new spawns, still clamps to [0.05, 4.0].
// v0.648: Plan H-P0 -- Vehicle Health Multiplier slider on the Ready Dialog. New knob (5%-400%, step 1%) on the same row as Mode Settings, positioned to the LEFT of the Aircraft Ceiling block: [<] Health:NNN% [>] then Mode Settings row continues. Storage: float in (0, 4], confirmed-only (only takes effect after the user clicks Confirm), applied to NEW vehicle spawns via mod.SetVehicleMaxHealthMultiplier at the end of OnVehicleSpawned (wrapped in try/catch per the BillDukes VehicleUIUniversal precedent). Per-map default wired into MapConfig.defaultVehicleHealthMultiplier (all 9 maps explicit at 1.0 today; future maps can override). Touching the knob flips game-mode to Custom (matches ceiling pattern); picking a preset resets the knob to the map default. Reset / Fresh Setup preserves the confirmed value (matches existing ceiling/vehicles behavior). Settings-summary HUD line "Vehicle Health: NNN%" always shown. World-log broadcast "{player} changed the Vehicle Health to NNN%" on Confirm when value changes. Also retrofitted the two sibling broadcasts (aircraftCeilingChanged + gameModeChanged) to wrap changedBy via safePlayerArg -- they were missed by the v0.634 CQ_Bug_94 defensive pass. Plan: design_doc/5.27.26_heli_vehicle_health_multiplier_plan.md.
// v0.647: Extend CQ_Bug_42 guards to two more unguarded mod.GetVariable(regVehiclesTeam1/2) callsites that the v0.646 helper-only fix missed. (1) clock.ts getRegisteredVehicleCount: was passing mod.GetVariable(...) directly to mod.CountOf() without a null guard. Called twice per main-loop tick (Team1 + Team2) inside the live-round gate -- when a player joins mid-round, the first tick after their join fires 2 errors matching the user-observed "exactly 2 errors on join in MP server" pattern. Added `if (!arr) return 0;` guard. (2) vehicles.ts registerVehicleToTeam: was passing mod.GetVariable(...) directly to mod.AppendToArray() in two paired Team1/Team2 branches. Coerced to mod.EmptyArray() via `?? mod.EmptyArray()` before append. Pure defensive guards, zero behavior change on valid-array path. Same fix family as v0.646; just covers more callsites Conquest's array-helpers consolidation took care of via different code shape.
// v0.646: Port Conquest CQ_Bug_42 v1.073 fix for the 2 "Received undefined values" engine errors at game start. Source: mod.GetVariable(regVehiclesTeam1/2) can return a non-array during transient registry state, and Helis's arrayContainsVehicle/arrayRemoveVehicle helpers in vehicles.ts pass the undefined arr directly to modlib.IsTrueForAny / modlib.FilteredArray which internally call mod.CountOf(undefined) -> "Received undefined values as arguments" engine error. Once per team registry = exactly 2 errors (matches observed count). Fix: defensive guards at the helper level -- arrayContainsVehicle returns false when arr is falsy; arrayRemoveVehicle returns mod.EmptyArray() when arr is falsy. Pure defensive guards, zero behavior change on valid-array path. Conquest also added a similar guard at capture-tickets.ts but Helis-only does not have that code path. Also reverted v0.645's 50ms mod.Wait at the top of OnVehicleSpawned -- that was speculation that the position read was firing the error; CQ_Bug_42 prior art identifies the actual source as the registry helpers, not GetObjectPosition. Found via static analysis comparing Helis vehicles.ts:6-13 to Conquest's array-helpers.ts (post-v1.073).
// v0.645: Option B fix attempt for "Received undefined values" errors (2 per game start) -- added 50ms `await mod.Wait(0.05)` at the top of OnVehicleSpawned before the first mod.GetObjectPosition(eventVehicle) call. Static analysis (post-probe) identified this unconditional position read at line 568 as the most likely source: engine can deliver OnVehicleSpawned before the vehicle transform is fully set, and reading position too early on a just-spawned vehicle fires the engine error log. Conquest avoids this by token-binding via bindSpawnedVehicleToExpectingSlot(vehicle) first and only reading position after a successful bind (vehicle-events.ts:67-71); Helis's bindSpawnedVehicleToSlot still needs vehiclePos for its position-fallback path, so we can't simply defer / skip the read. Smallest-risk fix is to give the engine 50ms to settle before any position query. If errors persist after v0.645 testing, consider Option A (restructure OnVehicleSpawned to defer the position read until after the inline token-bind shortcut, mirroring Conquest's architecture).
// v0.644: Plan A11 cleanup -- probe instrumentation (v0.639 thru v0.643) removed entirely. HUD widget + dev-console correlation proved non-viable as a debug path: console is behind menus, HUD widget is in-game, user cannot view both simultaneously. Reverted ALL probe code: stripped 96 call sites (73 in index.ts, 19 in team-switch.ts, 4 in hud.ts), removed _probeStamp/_probeStampW/_stampIdFromName/_ensureProbeWidget helpers + State.debug.lastProbeStep / probeStepCount fields from state.ts. Substantive fixes from v0.638 (isAliveByPid cache + 6 callsite guards), v0.634 (safePlayerArg), v0.633 (RemoveEquipment drop + roundend loop gates), v0.632 (getUiSafePlayerMessage + DEPLOY_SETTLE_GRACE_SECONDS), v0.631 (safeUndeployPlayer) all preserved. Next: static analysis comparing Conquest vs Helis paired-op surfaces at game start (OGMS, OnVehicleSpawned, startVehicleSpawnerSystem) to identify the source of the 2 "Received undefined values" errors via code-level divergence.
// v0.643: Plan A11 broad slow-mode -- v0.642 confirmed errors fire from a path OUTSIDE spawnTeamSwitchInteractPoint (function progressed cleanly 601-618 with errors still occurring). Added _probeStampW(name) async helper that stamps + awaits 0.5s. Bulk-replaced `_probeStamp(` -> `await _probeStampW(` in index.ts (73 sites: OGMS + OPJG + OPDEP + OVS) and team-switch.ts (19 STIP sites). Removed the 17 redundant explicit `await mod.Wait(0.5)` calls from STIP (now handled inside _probeStampW). Game start now takes ~45s but every stamp holds 0.5s visible. User reports the last visible stamp ID (1xx/2xx/3xx/4xx/6xx) on the HUD when each of the 2 "Received undefined values" errors appears in dev console.
// v0.642: Plan A11 slow-mode -- v0.641 user caught stamp 603 (just before 1.5s mod.Wait) then settled on 312, meaning STIP stamps 604-619 fired too fast to read. Added 0.5s mod.Wait between every STIP stamp inside spawnTeamSwitchInteractPoint so each stamp holds long enough to read visually. Function takes ~9 extra seconds during spawn-in (acceptable for debug). User watches widget tick through 601...619 and reports the last STIP integer visible when each of the 2 "Received undefined values" errors appears in the dev console. No console.log path available (user confirmed dev console not visible to them).
// v0.641: Plan A11 narrowing -- v0.640 probe identified that the 2 "Received undefined values" errors fire inside OnPlayerDeployed, specifically between stamps 311 (OPDEP_11_BEFORE_SPAWN_INTERACT) and 312 (OPDEP_12_AFTER_SPAWN_INTERACT). That window is the body of spawnTeamSwitchInteractPoint(eventPlayer) in team-switch.ts. Added STIP_NN stamps (prefix maps to 600+NN) at every mod.* call site inside that function: STIP_01-19 covering enter, deploy-settle wait, branch check, safeGetSoldierStateBool(IsOnGround), while loop, position/facing reads, mod.Add chain, mod.SpawnObject(InteractPoint), mod.EnableInteractPoint. Added STIP=600 to _stampIdFromName parser. Run again and report the LAST STIP integer (601-619) the widget shows when the 2 errors appear.
// v0.640: Plan A11 fix -- v0.639 probe widget displayed "unknown string" because mod.Message treats string args as string-key lookups (per existing memory: "Literal strings produce 'unknown string'; must use mod.stringkeys.* from strings.json"). Switched probe display to NUMERIC ID parsed from the stamp name: prefix maps to a 100-bucket base (OGMS=100, OPJG=200, OPDEP=300, OVS=400, ENSUREHUD=500), suffix is the local NN. Example: OGMS_09_BEFORE_BROADCAST_INIT_T1 -> ID 109. Added _stampIdFromName(name) parser. mod.Message receives the numeric id via genericCounter "{0}" -- same pattern that safeSetUITextLabel + setCounterText use successfully across the codebase. Source-only change to state.ts; no call sites edited.
// v0.639: Plan A11 -- TEMPORARY probe instrumentation to locate the source of the 2 "Received undefined values as arguments" engine errors at game/round start. After v0.637 mass migration of 57 mod.SetUITextLabel callsites did NOT fix the errors, an audit revealed Conquest only partially uses the safe-wrapper pattern (90% wrapped for SetUIWidgetVisible/SetUITextColor; sparse for other UI APIs), making a blind mass-migration of 200+ direct mod.SetUI* / mod.AddUI* callsites a guess rather than a Conquest port. Probe adds: State.debug.lastProbeStep + probeStepCount; _probeStamp(name) helper that increments counter, console.logs "[PROBE NN] name", and updates a per-player widget; _ensureProbeWidget(player) builds a top-left HUD text widget; ENABLE_PROBE constant gates the entire system. Instrumented checkpoints across OnGameModeStarted (~37 stamps), OnPlayerJoinGame (~19 stamps), OnPlayerDeployed (~12 stamps), OnVehicleSpawned (~4 stamps), and ensureHudForPlayer entry/fast-path/slow-path branches. User watches the HUD widget at game start; the LAST stamp displayed before the engine error appears in dev console indicates the section where the bad call lives. To be removed in v0.640 after source confirmed.
// v0.638: Plan A10 -- port Conquest CQ_Bug_37/38 v1.074 cache-guard pattern for the "ERROR REPORTED BY GETSOLDIERSTATE WHILE: Failed to apply action to player due to player not being deployed" engine error on plain death + round end. Added State.players.isAliveByPid: Record<number, boolean> cache + isPlayerAlive(player) helper in state.ts. Cache mutations: flipped TRUE in OnPlayerDeployed; flipped FALSE in OnPlayerUndeploy, OnPlayerLeaveGame (delete), OnVehicleDestroyed (proactive flip via popLastDriver for the vehicle's victim - closes race window before OnPlayerUndeploy fires), and both safe-wrapper catch blocks (self-healing alongside existing deployedByPid flip). Callsite guards at 6 per-tick paths now check isPlayerAlive before invoking safeGetSoldierState*: team-switch.ts isVelocityBeyond, team-switch.ts checkTeamSwitchInteractPointRemoval (IsDead read), utils.ts InteractMultiClickDetector.checkMultiClick (IsInteracting read), ready-dialog.ts applyAutoReadyForPid (IsInVehicle read), ready-dialog.ts checkTakeoffLimitForAllPlayers (GetPosition read), hud.ts updateHelpTextVisibilityForPid (IsInVehicle read, paired with existing deploy-grace from Plan A2), overtime.ts syncOvertimePlayerVehicleState (IsInVehicle read). Per Conquest's own caveat the first-tick race still fires the engine log; subsequent ticks skip immediately. Plan: design_doc/5.27.26_heli_isAliveByPid_cache_plan.md.
// v0.637: Plan A9 -- mass migration of direct mod.SetUITextLabel calls to safeSetUITextLabel wrapper. 57 direct callsites across clock.ts (4), hud.ts (10 plus 1 preserved inside the wrapper itself), ready-dialog.ts (42) were all bypassing the hardened safeSetUITextLabel wrapper from v0.636 -- the wrapper's null/undefined guard was dead code. This is the missing v0.763 half of Conquest's CQ_Bug_18 fix ("route the remaining ready-dialog and shared HUD label refresh paths through safe text setters"). Conquest has only 2 direct mod.SetUITextLabel calls in its entire codebase (both try/catch wrapped); Helis had 57. All migrated callsites now silently skip when label is undefined/null and re-resolve stale widget refs by name. Closes "Received undefined values as arguments" engine error class on UI text writes from previously-bypassing callers. No behavior change on success path.
// v0.636: Plan A8 -- port Conquest CQ_Bug_18 v0.764 safeSetUITextLabel hardening into hud.ts. Added isUITextWidget(widget) probe via mod.GetUITextSize, resolveLiveUITextWidget(widget) re-resolution by name, and widened safeSetUITextLabel to accept mod.Message | number | undefined | null with `if (label === undefined || label === null) return;` guard plus numeric-key normalization. 84+ existing callers benefit transparently. Closes "Received undefined values as arguments" engine error class on UI text writes (callers passing undefined labels during transient UI lifecycle transitions are now silently skipped before reaching the engine). Honest residual: the "GetSoldierState... player not being deployed" engine log on plain death (#2) is documented in conquest_issues.md CQ_Bug_37/38/50 as "engine-logs-before-JS-catch residue remains cosmetic"; Helis already has the same safe-wrapper pattern and inherits the same cosmetic log. Plan: design_doc/5.27.26_heli_safesetuitextlabel_hardening_plan.md.
// v0.635: Plan A7 -- dropped the vehicleSpawned broadcast at OnVehicleSpawned (index.ts). The broadcast read coords via mod.GetVehicleState(VehiclePosition) which can be invalid right after async spawn -- Math.floor(mod.XComponentOf(undefined)) = NaN, triggering "Received undefined values as arguments" engine errors (2 per round start in 1v1 default = 2 vehicle spawns). Conquest gates this exact broadcast behind FEATURE_PERF_DIAG (vehicle-events.ts:84-89); Helis equivalent is to drop it. The "vehicle registered for {team} by {player}" broadcast on vehicle entry (separate path) is unaffected and remains the gameplay-relevant scoring confirmation. Plan: design_doc/5.27.26_heli_vehicle_spawned_broadcast_drop_plan.md.
// v0.634: Plan A6 -- defensive Player-as-format-arg wrap across all mod.Message call sites that pass a raw Player ref. Added safePlayerArg(player) helper in state.ts; migrated 14 call sites across index.ts (PENDING_TEAM x2, registration arg0/arg1 block), team-switch.ts (PLAYER_READIED_UP, bestOfChanged x2, adminPanel.accessed), hud.ts (adminPanel.actionPressed), ready-dialog.ts (playersChanged, matchupChanged, PLAYER_AUTO_READIED_UP, overLine.title x2). Closes the residual "Received undefined values as arguments" engine error class regardless of which specific Player ref goes stale (Conquest #94 mechanism). Also dropped extra arg from 3 zero-placeholder subtitle calls at ready-dialog.ts:3392/3837/3917. Plan: design_doc/5.27.26_heli_player_arg_safety_plan.md.
// v0.633: Two more engine-error-log fixes ported from Conquest (P0-2 family). (1) Plan A3: drop the 2 mod.RemoveEquipment calls in OnPlayerDeployed; wrap the 2 mod.AddEquipment calls in try/catch. AddEquipment clobbers cleanly (Conquest v1.448 / #94 finding) -- the prior RemoveEquipment fired engine errors on empty gadget slots at first deploy ("Received undefined values as arguments", 2 instances per first deploy). (2) Plan A4: extend the guard in checkTakeoffLimitForAllPlayers and applyAutoReadyForAllPlayers to also skip during phase != NotReady and during cleanupActive. Eliminates "GETSOLDIERSTATE... player not being deployed" engine logs during the post-death undeploy race when the 1Hz master loop ran these pregame-only functions during GameOver / cleanup phases. Skip-path is faster (early return vs full AllPlayers iteration). Plans: design_doc/5.27.26_heli_remove_equipment_drop_plan.md + 5.27.26_heli_roundend_loop_gates_plan.md.
// v0.632: Two spawn-time engine-error fixes ported from Conquest. (1) Add getUiSafePlayerMessage helper in state.ts; use in getRosterEntryNameMessage to guard stale Player refs from "Received undefined values as arguments" engine logs (Conquest roster-active.ts:100 + id-helpers.ts:152 pattern). (2) Add DEPLOY_SETTLE_GRACE_SECONDS (1.5s) + State.players.deployedAtSecondsByPid timestamp; stamp in OnPlayerDeployed and clear in OnPlayerLeaveGame; inline grace check at the 2 race-window call sites in hud.ts (updateHelpTextVisibilityForPid IsInVehicle read) and team-switch.ts (spawnTeamSwitchInteractPoint pre-SoldierState wait). Eliminates "GetSoldierState... player not being deployed" engine logs during deploy race window (Conquest GCZ_DEPLOY_GRACE_SECONDS pattern from boundary/enforcement.ts). Plans: design_doc/5.27.26_heli_roster_validity_plan.md + 5.27.26_heli_deploy_settle_plan.md.
// v0.631: Wrap all mod.UndeployPlayer call sites in new safeUndeployPlayer helper (isPlayerDeployed precheck + try/catch). Eliminates cosmetic engine error logs on already-undeployed players; ports Conquest #36 / #39 defense pattern. 4 call sites updated across index.ts (deferForcedUndeploy), team-switch.ts (forceUndeployPlayer), round-flow.ts (round-end cleanup loop). No behavior change on success or engine-throw paths. Plan: design_doc/5.27.26_heli_undeployplayer_guards_plan.md.
// v0.630: Port conquest's build pipeline passes into helis-only. Added BOM strip, full-line + block-comment strip, indentation strip, blank-line collapse, modlib source inlining (via new src/foundation/modlib.ts), header re-injection from src/header-file.ts, EOF version line restore, and non-ASCII guardrail. Adopted conquest's relaxed verify.js (existence + size + JSON validity) with strict byte-compare opt-in via VERIFY_GROUND_TRUTH=1, plus 1 MB bundle size cap. Dead-code elimination pass intentionally skipped (no FEATURE_* flags in helis source). Bundle dropped from 708,998 -> ~500,000 bytes (~30% reduction). No runtime behavior change. Also split Changelog/History, Gamemode Description, Improvements punchlist, and Portal Naming Notes out of header-file.ts into separate source-only files mirroring conquest's organization. Switched // policy: prefix to // *policy: so postbuild strips them from the bundle.
// v0.623: We're using TS Template project now, thanks to @Dox and @MikeDeluca
// v0.621: Adjusted Aircraft Ceilings for Ladder based on feedback
// v0.620: Helis Alpha Candidate 1.0 release for 2v2 Ladder opening
// v0.616: Fix gamemode settings with some minor UI tweaks
// v0.608: Add helis-only H flag selection + per-mode overtime zones
// v0.592: Add admin tie-breaker mode toggle (last round/all/disabled) along with more game mode controls and customizations
// v0.591: Add takeoff limit gating + overtakeoff messaging (HUD floor + 20)
// v0.577: Add reset button + heli spawn overrides tied to confirm
// v0.568: Aircraft ceiling config per map + custom override controls for game modes
// v0.567: Map configs now support heli spawns and mode-based selection
// v0.544: Playtest ready, Alpha Candidate for 1.0....
// v0.543: Guard join-prompt deletes + defer forced undeploy to avoid deploy lifecycle crashes
// v0.541: Avoid hard-deleting overtime HUD on undeploy; hide + drop refs for safe rebuild
// v0.539: Code cleanup, regions added, 1.0 Alpha Release candidate
// v0.538: UI saftey wrappers, reorganized code, fixed disconnect Bugs, map crash bugs and UI inconsistencies with timing. Alpha candidate for 1.0 release.
// v0.514: UI/UX Polish, capture bar progress % display, tie-breaker tip added
// v0.477: Playtesting version, alpha candidate for 1.0 release
// v0.468: Added Admin function for overriding random tie-breaker flag for testing
// v0.443: Polished Tie-Breaker UI, capture zone rates, messaging and UX of capturing
// v0.457: Half-time flag visibility + capture tuning
// v0.395: Add overtime flag capture tiebreaker (randomized capture point + UI + capture logic)
// v0.359: Require triple-tap to unlock join prompt tips
// v0.358: Add join prompt tips sequence with unlock gating and per-player state
// v0.357: Hide help/ready text while undeployed to avoid respawn overlay & fixed issues smaller aspect ratios or wierd resolutions due to dialog overlap
// v0.346: Added MIT Licence and ensured spawn-disabled warning is shown while undeployed during live rounds for context
// v0.340: Tweak HUD counter sizes, add victory crown + dynamic roster height + debug roster placeholders
// v0.337: Added round-win crown and trending winner crown icons inside top HUD panels
// v0.333: Added rosters to the bottom of the map victory dialog for improved UX / Screenshot auditing
// v0.330: Cleaned up top HUD, made round scores more obvious, refactored some logic around ready status displays
// v0.322: Cleaned up UI spacings, colors, constants, positions and opacity - most things controlled via constants now
// v0.271: Added first-join help prompt overlay, controlled with SHOW_HELP_TEXT_PROMPT_ON_JOIN
// v0.269: Disable respawn during live rounds with DISABLE_RESPAWN_DURING_LIVE_ROUND
// v0.266: Increased triple tap window to 2s, instead of 1s. Clarified string to mention "standing still" while triple tapping.
// v0.263: Fix for ready up roster refreshing when new player joins or old player disconnects
// v0.262: Refactored round end process. Destroy all tanks, force undeploy all players, respawn all tanks, wait, force redeploy players, keep Round End dialog up longer
// v0.259: Release version for Ladder with 8 maps
// v0.258: Added MapConfig settings for Area 22B
// v0.257: Fixed race condition on first tank spawned - need to clear it and spawn correct vehicle to avoid default Abrams spawn
// v0.247: Added team names to MapConfig, fixed backend JS Errors on player being deployed or not (empty string args {} vs {0})
// v0.240: Fixed spawner logic regressions (spawn block and failed to spawn with rapid mode increase)
// v0.238: Submitted for Code Review by Dox & Poly
// v0.233: Code cleanup, reorganization and comment clarity, prepping for 1.0 Release version
// v0.228: Added dynamic binding to modes: 1v1 only spawns 1 tank, 4v4 spawns 4 tanks. Configurable when round is not live.
// v0.224: Added Map Detector logic to auto-detect which MapConfig and spawners to use, then display the Map name on the Ready Up screen
// v0.218: First pass on Spawn points for all 7 maps in Ladder rotation, using Admin Debug Position tool
// v0.217: Added Admin Debug Position button to display X/Y/Z coordinates and Y rotation of player
// v0.205: Added spawn camp scoring protection if a leftover vehicle remains in main base during round setup
// v0.197: Adjusted some HUD/UI positions, added new labels and added "1v1" up to "4v4" matchup configuration buttons to Ready screen
// v0.182: Functional version of Badlands working with respawn logic, orientation and vehicle assignments working
// v0.177: Custom respawn logic implemented with unique data structures per map; custom vehicle and HQ spawn points needed per map
// v0.152: Forcing supply boxes on every spawn, to ensure no other gadget loophole
// v0.151: Finalized string.json into new format with updated strings policy
// v0.148: Added Changelog / History section to script header and finalized enum/interface refactor bugs
// v0.134: Last working version before enum/interface refactor (see archive\enum_interface_implementation_plan.md)
// v0.129: Release version for Ladder with 7 maps
// v0.059: Last version before switching primarly from GPT-5.2 web client to GPT-5.2-Codex in VS Code

//#endregion ----------------- Changelog / History --------------------
