// @ts-nocheck
// Module: ui/conquest/hud-core/constants -- single-source layout constants for hard-cut combat HUD

const TWL_CONQUEST_HUD_MAIN_UPDATE_SECONDS = 0.12;
const TWL_CONQUEST_HUD_ANIMATION_UPDATE_SECONDS = 0.12;

const TWL_CONQUEST_HUD_ROOT_WIDTH = TOP_HUD_ROOT_WIDTH;
const TWL_CONQUEST_HUD_ROOT_HEIGHT = TOP_HUD_ROOT_HEIGHT;
const TWL_CONQUEST_HUD_ROOT_HIDDEN_Y = -2000;

const TWL_CONQUEST_HUD_OBJECTIVE_SLOT_COUNT = 7;
const TWL_CONQUEST_HUD_OBJECTIVE_SLOT_WIDTH = CONQUEST_HUD_FLAG_SLOT_WIDTH;
const TWL_CONQUEST_HUD_OBJECTIVE_SLOT_HEIGHT = CONQUEST_HUD_FLAG_SLOT_HEIGHT;
const TWL_CONQUEST_HUD_OBJECTIVE_SLOT_STEP_X = 35;

const TWL_CONQUEST_HUD_TICKETS_WIDTH = 561.77;
const TWL_CONQUEST_HUD_TICKETS_HEIGHT = 50;
const TWL_CONQUEST_HUD_TICKETS_X = 0;
const TWL_CONQUEST_HUD_TICKETS_Y = 0;

const TWL_CONQUEST_HUD_OBJECTIVES_WIDTH = 238.5;
const TWL_CONQUEST_HUD_OBJECTIVES_HEIGHT = 46;
const TWL_CONQUEST_HUD_OBJECTIVES_X = 0;
const TWL_CONQUEST_HUD_OBJECTIVES_Y = 0;

const TWL_CONQUEST_HUD_COMBAT_WIDTH = TWL_CONQUEST_HUD_TICKETS_WIDTH;
const TWL_CONQUEST_HUD_COMBAT_HEIGHT = 180;
const TWL_CONQUEST_HUD_COMBAT_X = 0;
// Inferred from legacy layout and current screenshot deltas:
// keep one root-level drop knob for the full combat stack (tickets/flags/popout/engage).
const TWL_CONQUEST_HUD_TOP_STACK_OFFSET_Y = 24;
const TWL_CONQUEST_HUD_COMBAT_Y = CONQUEST_HUD_TICKETS_FLAGS_SHIFT_Y + TWL_CONQUEST_HUD_TOP_STACK_OFFSET_Y;

const TWL_CONQUEST_HUD_TICKET_BOX_WIDTH = 72;
const TWL_CONQUEST_HUD_TICKET_BOX_HEIGHT = 28;
const TWL_CONQUEST_HUD_TICKET_BOX_ALPHA = 0.75;
// v1.451: TWL_CONQUEST_HUD_TEXT_BOX_PADDING removed. Was only used by the team-name backplates
// for horizontal padding; team-name backplates were dropped entirely in v1.451 (looked weird
// in top-HUD spacing, team names not load-bearing UI). Engage-status backplate uses dedicated
// ENGAGE_STATUS_BOX_* constants below — re-add a generic padding constant only when a NEW
// backplate surface needs it.
const TWL_CONQUEST_HUD_TICKET_COUNT_WIDTH = 72;
const TWL_CONQUEST_HUD_TICKET_COUNT_HEIGHT = 28;
const TWL_CONQUEST_HUD_TICKET_COUNT_TEXT_SIZE = 26;
const TWL_CONQUEST_HUD_TICKET_TEAM_LABEL_WIDTH = 96;
const TWL_CONQUEST_HUD_TICKET_TEAM_LABEL_HEIGHT = 28;
const TWL_CONQUEST_HUD_TICKET_TEAM_LABEL_TEXT_SIZE = 18;
const TWL_CONQUEST_HUD_TICKET_TEAM_LABEL_GAP_X = 12;
const TWL_CONQUEST_HUD_TICKET_SLASH_WIDTH = 16;
const TWL_CONQUEST_HUD_TICKET_SLASH_HEIGHT = 28;
const TWL_CONQUEST_HUD_TICKET_SLASH_TEXT_SIZE = 22;
const TWL_CONQUEST_HUD_TICKET_SLASH_X = Math.floor((TWL_CONQUEST_HUD_TICKETS_WIDTH - TWL_CONQUEST_HUD_TICKET_SLASH_WIDTH) / 2);
const TWL_CONQUEST_HUD_TICKET_SLASH_Y = 0;

// Legacy-parity horizontal spacing model:
// ticket clusters move outward so the center gap tracks the visible flag row span.
const TWL_CONQUEST_HUD_CENTER_GAP_BASE = 284.90 - (103.39 + CONQUEST_HUD_TICKET_BAR_WIDTH);
const TWL_CONQUEST_HUD_FLAGS_TO_TICKET_GAP_X = Math.max(
    0,
    TWL_CONQUEST_HUD_OBJECTIVE_SLOT_STEP_X - TWL_CONQUEST_HUD_OBJECTIVE_SLOT_WIDTH
);
const TWL_CONQUEST_HUD_TICKET_BLUE_COUNT_X_BASE = (40 - 12) + 2;
const TWL_CONQUEST_HUD_TICKET_BLUE_COUNT_Y = 21;
const TWL_CONQUEST_HUD_TICKET_RED_COUNT_X_BASE = 461.39 - 2;
const TWL_CONQUEST_HUD_TICKET_RED_COUNT_Y = 21;
const TWL_CONQUEST_HUD_TICKET_TEAM_LABEL_ROOT_Y = TWL_CONQUEST_HUD_COMBAT_Y + TWL_CONQUEST_HUD_TICKET_BLUE_COUNT_Y;

const TWL_CONQUEST_HUD_TICKET_BLUE_BAR_X_BASE = 103.39;
// Pixel-snap the shared ticket-bar Y so both bars render on the exact same scanline.
const TWL_CONQUEST_HUD_TICKET_BAR_Y = Math.round(30.82);
const TWL_CONQUEST_HUD_TICKET_BLUE_BAR_Y = TWL_CONQUEST_HUD_TICKET_BAR_Y;
const TWL_CONQUEST_HUD_TICKET_RED_BAR_X_BASE = 284.90;
const TWL_CONQUEST_HUD_TICKET_RED_BAR_Y = TWL_CONQUEST_HUD_TICKET_BAR_Y;
// Integer-size ticket bars prevent fractional-size edge seams between track/fill on some clients.
const TWL_CONQUEST_HUD_TICKET_BAR_WIDTH = Math.round(CONQUEST_HUD_TICKET_BAR_WIDTH);
const TWL_CONQUEST_HUD_TICKET_BAR_HEIGHT = Math.round(CONQUEST_HUD_TICKET_BAR_HEIGHT);
const TWL_CONQUEST_HUD_TICKET_LEAD_BORDER_GROW = CONQUEST_HUD_TICKET_LEAD_BORDER_GROW;
const TWL_CONQUEST_HUD_TICKET_LEAD_BORDER_ALPHA = CONQUEST_HUD_TICKET_LEAD_BORDER_ALPHA;
const TWL_CONQUEST_HUD_TICKET_LEAD_CROWN_SIZE = CONQUEST_HUD_TICKET_LEAD_CROWN_SIZE;
const TWL_CONQUEST_HUD_TICKET_LEAD_CROWN_GAP_Y = CONQUEST_HUD_TICKET_LEAD_CROWN_GAP_Y;
const TWL_CONQUEST_HUD_TICKET_LEAD_CROWN_SHADOW_GROW = 5;
const TWL_CONQUEST_HUD_TICKET_LEAD_CROWN_SHADOW_ALPHA = 0.82;
const TWL_CONQUEST_HUD_TICKET_LEAD_CROWN_SHADOW_TOP_BIAS = -0.5;
const TWL_CONQUEST_HUD_TICKET_LEAD_CROWN_SHADOW_CENTER_SHIFT = TWL_CONQUEST_HUD_TICKET_LEAD_CROWN_SHADOW_GROW / 2;
const TWL_CONQUEST_HUD_TICKET_LEAD_CROWN_SHADOW_SIZE = TWL_CONQUEST_HUD_TICKET_LEAD_CROWN_SIZE + TWL_CONQUEST_HUD_TICKET_LEAD_CROWN_SHADOW_GROW;
const TWL_CONQUEST_HUD_TICKET_LEAD_CROWN_Y = TWL_CONQUEST_HUD_TICKET_BLUE_COUNT_Y
    - (TWL_CONQUEST_HUD_TICKET_LEAD_CROWN_SIZE + TWL_CONQUEST_HUD_TICKET_LEAD_CROWN_GAP_Y);
const TWL_CONQUEST_HUD_TICKET_LEAD_CROWN_SHADOW_Y = TWL_CONQUEST_HUD_TICKET_LEAD_CROWN_Y
    - TWL_CONQUEST_HUD_TICKET_LEAD_CROWN_SHADOW_CENTER_SHIFT
    + TWL_CONQUEST_HUD_TICKET_LEAD_CROWN_SHADOW_TOP_BIAS;
const TWL_CONQUEST_HUD_TICKET_BLEED_CHEVRON_COUNT = CONQUEST_HUD_TICKET_BLEED_CHEVRON_COUNT;
const TWL_CONQUEST_HUD_TICKET_BLEED_CHEVRON_WIDTH = CONQUEST_HUD_TICKET_BLEED_CHEVRON_WIDTH;
const TWL_CONQUEST_HUD_TICKET_BLEED_CHEVRON_HEIGHT = CONQUEST_HUD_TICKET_BLEED_CHEVRON_HEIGHT;
const TWL_CONQUEST_HUD_TICKET_BLEED_CHEVRON_TEXT_SIZE = CONQUEST_HUD_TICKET_BLEED_CHEVRON_TEXT_SIZE;
const TWL_CONQUEST_HUD_TICKET_BLEED_CHEVRON_Y = TWL_CONQUEST_HUD_TICKET_BLUE_BAR_Y
    + Math.floor((TWL_CONQUEST_HUD_TICKET_BAR_HEIGHT - TWL_CONQUEST_HUD_TICKET_BLEED_CHEVRON_HEIGHT) / 2)
    + CONQUEST_HUD_TICKET_BLEED_CHEVRON_IN_BAR_OFFSET_Y
    - 1;
const TWL_CONQUEST_HUD_TICKET_BLEED_STEP_X = CONQUEST_HUD_TICKET_BLEED_CHEVRON_STEP_X;

type TwlConquestHudTicketLayout = {
    layoutFlagCount: number;
    outwardShiftX: number;
    blueCountX: number;
    redCountX: number;
    blueBarX: number;
    redBarX: number;
    leadLeftCrownX: number;
    leadRightCrownX: number;
    leadLeftCrownShadowX: number;
    leadRightCrownShadowX: number;
    bleedLeftStartX: number;
    bleedRightStartX: number;
};

// Resolves the live objective-count input used by ticket/objective spacing.
function twlConquestHudGetLayoutFlagCount(): number {
    const mappedCount = State?.conquest?.capture?.mappedObjIdsInOrder?.length ?? 0;
    const configuredCount = ACTIVE_CAPTURE_POINT_CONFIGS.length;
    const count = mappedCount > 0 ? mappedCount : configuredCount;
    return Math.max(1, Math.min(TWL_CONQUEST_HUD_OBJECTIVE_SLOT_COUNT, count));
}

// Computes all ticket-lane X positions from one runtime layout sample so placement tracks active map objective count.
function twlConquestHudBuildTicketLayout(): TwlConquestHudTicketLayout {
    const layoutFlagCount = twlConquestHudGetLayoutFlagCount();
    const visibleFlagSpanWidth = TWL_CONQUEST_HUD_OBJECTIVE_SLOT_WIDTH
        + ((layoutFlagCount - 1) * TWL_CONQUEST_HUD_OBJECTIVE_SLOT_STEP_X);
    const centerGapTarget = visibleFlagSpanWidth + (TWL_CONQUEST_HUD_FLAGS_TO_TICKET_GAP_X * 2);
    const outwardShiftX = Math.max(0, (centerGapTarget - TWL_CONQUEST_HUD_CENTER_GAP_BASE) / 2);
    // Pixel-snap all ticket-lane X coordinates so counters/bars share exact integer placement.
    const blueCountX = Math.round(TWL_CONQUEST_HUD_TICKET_BLUE_COUNT_X_BASE - outwardShiftX);
    const redCountX = Math.round(TWL_CONQUEST_HUD_TICKET_RED_COUNT_X_BASE + outwardShiftX);
    const blueBarX = Math.round(TWL_CONQUEST_HUD_TICKET_BLUE_BAR_X_BASE - outwardShiftX);
    const redBarX = Math.round(TWL_CONQUEST_HUD_TICKET_RED_BAR_X_BASE + outwardShiftX);
    const leadLeftCrownX = blueCountX + ((TWL_CONQUEST_HUD_TICKET_BOX_WIDTH - TWL_CONQUEST_HUD_TICKET_LEAD_CROWN_SIZE) / 2);
    const leadRightCrownX = redCountX + ((TWL_CONQUEST_HUD_TICKET_BOX_WIDTH - TWL_CONQUEST_HUD_TICKET_LEAD_CROWN_SIZE) / 2);
    const leadLeftCrownShadowX = leadLeftCrownX - TWL_CONQUEST_HUD_TICKET_LEAD_CROWN_SHADOW_CENTER_SHIFT;
    const leadRightCrownShadowX = leadRightCrownX - TWL_CONQUEST_HUD_TICKET_LEAD_CROWN_SHADOW_CENTER_SHIFT;
    const bleedLeftStartX = blueBarX + CONQUEST_HUD_TICKET_BLEED_CHEVRON_OUTER_INSET_X;
    const bleedRightStartX = redBarX
        + TWL_CONQUEST_HUD_TICKET_BAR_WIDTH
        - CONQUEST_HUD_TICKET_BLEED_CHEVRON_OUTER_INSET_X
        - TWL_CONQUEST_HUD_TICKET_BLEED_CHEVRON_WIDTH;
    return {
        layoutFlagCount,
        outwardShiftX,
        blueCountX,
        redCountX,
        blueBarX,
        redBarX,
        leadLeftCrownX,
        leadRightCrownX,
        leadLeftCrownShadowX,
        leadRightCrownShadowX,
        bleedLeftStartX,
        bleedRightStartX,
    };
}

function twlConquestHudGetTicketBlueTeamLabelRootX(ticketLayout: TwlConquestHudTicketLayout): number {
    const ticketsLeftX = Math.round(-(TWL_CONQUEST_HUD_TICKETS_WIDTH / 2));
    return Math.round(
        ticketsLeftX
        + ticketLayout.blueCountX
        - TWL_CONQUEST_HUD_TICKET_TEAM_LABEL_GAP_X
        - TWL_CONQUEST_HUD_TICKET_TEAM_LABEL_WIDTH
        + (TWL_CONQUEST_HUD_TICKET_TEAM_LABEL_WIDTH / 2)
    );
}

function twlConquestHudGetTicketRedTeamLabelRootX(ticketLayout: TwlConquestHudTicketLayout): number {
    const ticketsLeftX = Math.round(-(TWL_CONQUEST_HUD_TICKETS_WIDTH / 2));
    return Math.round(
        ticketsLeftX
        + ticketLayout.redCountX
        + TWL_CONQUEST_HUD_TICKET_BOX_WIDTH
        + TWL_CONQUEST_HUD_TICKET_TEAM_LABEL_GAP_X
        + (TWL_CONQUEST_HUD_TICKET_TEAM_LABEL_WIDTH / 2)
    );
}

const TWL_CONQUEST_HUD_OBJECTIVE_SLOT_Y = Math.round((
    TWL_CONQUEST_HUD_TICKET_BLUE_BAR_Y + (TWL_CONQUEST_HUD_TICKET_BAR_HEIGHT / 2)
) - (TWL_CONQUEST_HUD_OBJECTIVE_SLOT_HEIGHT / 2));
const TWL_CONQUEST_HUD_OBJECTIVE_FILL_INSET_X = CONQUEST_HUD_FLAG_FILL_INSET_X;
const TWL_CONQUEST_HUD_OBJECTIVE_FILL_INSET_Y = CONQUEST_HUD_FLAG_FILL_INSET_Y;
const TWL_CONQUEST_HUD_OBJECTIVE_FILL_WIDTH = TWL_CONQUEST_HUD_OBJECTIVE_SLOT_WIDTH - (TWL_CONQUEST_HUD_OBJECTIVE_FILL_INSET_X * 2);
const TWL_CONQUEST_HUD_OBJECTIVE_FILL_HEIGHT = TWL_CONQUEST_HUD_OBJECTIVE_SLOT_HEIGHT - (TWL_CONQUEST_HUD_OBJECTIVE_FILL_INSET_Y * 2);
const TWL_CONQUEST_HUD_OBJECTIVE_LABEL_TEXT_SIZE = 19;
const TWL_CONQUEST_HUD_OBJECTIVE_PERCENT_Y = TWL_CONQUEST_HUD_OBJECTIVE_SLOT_HEIGHT;
const TWL_CONQUEST_HUD_OBJECTIVE_PERCENT_WIDTH = TWL_CONQUEST_HUD_OBJECTIVE_SLOT_WIDTH;
const TWL_CONQUEST_HUD_OBJECTIVE_PERCENT_HEIGHT = 12;
const TWL_CONQUEST_HUD_OBJECTIVE_PERCENT_TEXT_SIZE = CONQUEST_HUD_FLAG_PERCENT_TEXT_SIZE;

const TWL_CONQUEST_HUD_POPOUT_ROOT_X = (TWL_CONQUEST_HUD_OBJECTIVES_WIDTH - CONQUEST_HUD_FLAG_ACTIVE_POPOUT_ROOT_WIDTH) / 2;
const TWL_CONQUEST_HUD_POPOUT_ROOT_Y = Math.round(59.62);
const TWL_CONQUEST_HUD_POPOUT_ROOT_WIDTH = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_ROOT_WIDTH;
const TWL_CONQUEST_HUD_POPOUT_ROOT_HEIGHT = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_ROOT_HEIGHT;
const TWL_CONQUEST_HUD_POPOUT_SLOT_X = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_SLOT_OFFSET_X;
const TWL_CONQUEST_HUD_POPOUT_SLOT_Y = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_SLOT_OFFSET_Y;
const TWL_CONQUEST_HUD_POPOUT_SLOT_WIDTH = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_SLOT_WIDTH;
const TWL_CONQUEST_HUD_POPOUT_SLOT_HEIGHT = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_SLOT_HEIGHT;
const TWL_CONQUEST_HUD_POPOUT_FILL_X = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_FILL_INSET_X;
const TWL_CONQUEST_HUD_POPOUT_FILL_Y = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_FILL_INSET_Y;
const TWL_CONQUEST_HUD_POPOUT_FILL_WIDTH = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_FILL_MAX_WIDTH;
const TWL_CONQUEST_HUD_POPOUT_FILL_HEIGHT = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_FILL_MAX_HEIGHT;
const TWL_CONQUEST_HUD_POPOUT_LABEL_TEXT_SIZE = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_LABEL_TEXT_SIZE;
const TWL_CONQUEST_HUD_POPOUT_PERCENT_X = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_OFFSET_X;
const TWL_CONQUEST_HUD_POPOUT_PERCENT_Y = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_OFFSET_Y;
const TWL_CONQUEST_HUD_POPOUT_PERCENT_WIDTH = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_ROOT_WIDTH;
const TWL_CONQUEST_HUD_POPOUT_PERCENT_HEIGHT = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_ROOT_HEIGHT;
const TWL_CONQUEST_HUD_POPOUT_PERCENT_TEXT_SIZE = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_TEXT_SIZE;

// Pixel-snap engage lane root to prevent sub-pixel anti-alias drift between left/right count chip gaps.
const TWL_CONQUEST_HUD_ENGAGE_ROOT_X = Math.round(
    TWL_CONQUEST_HUD_POPOUT_ROOT_X
    - ((CONQUEST_HUD_FLAG_ENGAGE_ROOT_WIDTH - CONQUEST_HUD_FLAG_ACTIVE_POPOUT_ROOT_WIDTH) / 2)
);
const TWL_CONQUEST_HUD_ENGAGE_ROOT_Y = Math.round(
    TWL_CONQUEST_HUD_POPOUT_ROOT_Y + CONQUEST_HUD_FLAG_ACTIVE_POPOUT_ROOT_HEIGHT
);
const TWL_CONQUEST_HUD_ENGAGE_ROOT_WIDTH = CONQUEST_HUD_FLAG_ENGAGE_ROOT_WIDTH;
const TWL_CONQUEST_HUD_ENGAGE_ROOT_HEIGHT = CONQUEST_HUD_FLAG_ENGAGE_ROOT_HEIGHT;
const TWL_CONQUEST_HUD_ENGAGE_TRACK_X = CONQUEST_HUD_FLAG_ENGAGE_TRACK_X;
const TWL_CONQUEST_HUD_ENGAGE_TRACK_Y = CONQUEST_HUD_FLAG_ENGAGE_TRACK_Y;
const TWL_CONQUEST_HUD_ENGAGE_TRACK_WIDTH = CONQUEST_HUD_FLAG_ENGAGE_TRACK_WIDTH;
const TWL_CONQUEST_HUD_ENGAGE_TRACK_HEIGHT = CONQUEST_HUD_FLAG_ENGAGE_TRACK_HEIGHT;
const TWL_CONQUEST_HUD_ENGAGE_FRIENDLY_COUNT_X = CONQUEST_HUD_FLAG_ENGAGE_FRIENDLY_COUNT_BG_X;
const TWL_CONQUEST_HUD_ENGAGE_ENEMY_COUNT_X = CONQUEST_HUD_FLAG_ENGAGE_ENEMY_COUNT_BG_X - 1;
const TWL_CONQUEST_HUD_ENGAGE_COUNT_Y = CONQUEST_HUD_FLAG_ENGAGE_COUNT_BG_Y;
const TWL_CONQUEST_HUD_ENGAGE_COUNT_WIDTH = CONQUEST_HUD_FLAG_ENGAGE_COUNT_BG_WIDTH;
const TWL_CONQUEST_HUD_ENGAGE_COUNT_HEIGHT = CONQUEST_HUD_FLAG_ENGAGE_COUNT_BG_HEIGHT;
const TWL_CONQUEST_HUD_ENGAGE_COUNT_TEXT_SIZE = CONQUEST_HUD_FLAG_ENGAGE_COUNT_TEXT_SIZE;
const TWL_CONQUEST_HUD_ENGAGE_STATUS_Y = CONQUEST_HUD_FLAG_ENGAGE_STATUS_Y;
const TWL_CONQUEST_HUD_ENGAGE_STATUS_WIDTH = CONQUEST_HUD_FLAG_ENGAGE_STATUS_WIDTH;
const TWL_CONQUEST_HUD_ENGAGE_STATUS_HEIGHT = CONQUEST_HUD_FLAG_ENGAGE_STATUS_HEIGHT;
const TWL_CONQUEST_HUD_ENGAGE_STATUS_TEXT_SIZE = CONQUEST_HUD_FLAG_ENGAGE_STATUS_TEXT_SIZE;
// Engage-status backplate (v1.450, iteratively tightened through v1.453): sized to just
// barely fit the longest status string ("NEUTRALIZING" — 12 chars at fontSize 18). The other
// 3 status strings (DEFEND/CAPTURING/CONTESTED) are shorter and center inside this box.
// Width history: 110 (v1.450) → 90 (v1.451, NEUTRALIZING clipped) → 98 (v1.452, snug fit).
// Height history: 22 → 18 (v1.452, full text bounding-box height) → 14 (v1.453, covers only
// the visible glyph cap-height; 18px widget bounding box has ~2px padding above + ~2px below
// the actual rendered all-caps glyphs that the box doesn't need to back). Y shifted down 2px
// in v1.453 so the top of the box no longer touches the engage-track bar above it.
const TWL_CONQUEST_HUD_ENGAGE_STATUS_BOX_WIDTH = 98;
const TWL_CONQUEST_HUD_ENGAGE_STATUS_BOX_HEIGHT = 14;
const TWL_CONQUEST_HUD_ENGAGE_STATUS_BOX_X = Math.floor(
    (TWL_CONQUEST_HUD_ENGAGE_STATUS_WIDTH - TWL_CONQUEST_HUD_ENGAGE_STATUS_BOX_WIDTH) / 2
);
const TWL_CONQUEST_HUD_ENGAGE_STATUS_BOX_Y = TWL_CONQUEST_HUD_ENGAGE_STATUS_Y + 2;
const TWL_CONQUEST_HUD_TICKET_BLEED_ALWAYS_VISIBLE = false;
const TWL_CONQUEST_HUD_PERCENT_BG_ALPHA = 0.75;
const TWL_CONQUEST_HUD_ENGAGE_COUNT_BG_ALPHA = 0.75;
const TWL_CONQUEST_HUD_OBJECTIVE_BORDER_ALPHA = 1;
const TWL_CONQUEST_HUD_POPOUT_BORDER_ALPHA = 1;

type TwlConquestHudShadowLayerProfile = {
    suffix: string;
    x: number;
    y: number;
};

// Wave 6 Ship 1c: returns empty profile to eliminate ALL combat HUD compass shadow rings
// (~280 widgets/pid reclaim, ~75% of M3 cache). The Ensure/Render/Hide/Delete consumers all
// iterate the profile, so empty-profile cascades to zero work without changing call sites.
// To restore: see reference_implementations/reference_conquest_attempt_d/src/ui/conquest/hud-core/constants.ts
// for the original 8-layer compass-direction ring builder.
function twlConquestHudBuildShadowRingProfile(): TwlConquestHudShadowLayerProfile[] {
    return [];
}

const TWL_CONQUEST_HUD_SHADOW_RING_PROFILE_PERCENT = twlConquestHudBuildShadowRingProfile();
const TWL_CONQUEST_HUD_SHADOW_RING_PROFILE_OBJECTIVE_LABEL = twlConquestHudBuildShadowRingProfile();
const TWL_CONQUEST_HUD_SHADOW_RING_PROFILE_POPOUT_PERCENT = twlConquestHudBuildShadowRingProfile();
const TWL_CONQUEST_HUD_SHADOW_RING_PROFILE_POPOUT_LABEL = twlConquestHudBuildShadowRingProfile();
const TWL_CONQUEST_HUD_SHADOW_RING_PROFILE_ENGAGE_STATUS = twlConquestHudBuildShadowRingProfile();
const TWL_CONQUEST_HUD_SHADOW_RING_PROFILE_ENGAGE_COUNT = twlConquestHudBuildShadowRingProfile();
const TWL_CONQUEST_HUD_SHADOW_RING_PROFILE_CHEVRON = twlConquestHudBuildShadowRingProfile();
const TWL_CONQUEST_HUD_SHADOW_RING_PROFILE_TEAM_LABEL = twlConquestHudBuildShadowRingProfile();

const TWL_CONQUEST_HUD_OBJECTIVE_SLOT_X_BY_INDEX: number[] = (() => {
    const xs: number[] = [];
    const centerIndex = (TWL_CONQUEST_HUD_OBJECTIVE_SLOT_COUNT - 1) / 2;
    const centeredLeftX = (TWL_CONQUEST_HUD_OBJECTIVES_WIDTH - TWL_CONQUEST_HUD_OBJECTIVE_SLOT_WIDTH) / 2;
    for (let i = 0; i < TWL_CONQUEST_HUD_OBJECTIVE_SLOT_COUNT; i++) {
        xs.push(Math.round(centeredLeftX + ((i - centerIndex) * TWL_CONQUEST_HUD_OBJECTIVE_SLOT_STEP_X)));
    }
    return xs;
})();

const TWL_CONQUEST_HUD_TICKET_BAR_TRACK_ALPHA = 0.9;
const TWL_CONQUEST_HUD_TICKET_BAR_FILL_ALPHA = 0.95;
const TWL_CONQUEST_HUD_OBJECTIVE_SLOT_ALPHA = 0.9;
const TWL_CONQUEST_HUD_OBJECTIVE_FILL_ALPHA = 0.95;
const TWL_CONQUEST_HUD_POPOUT_SLOT_ALPHA = 0.9;
const TWL_CONQUEST_HUD_POPOUT_FILL_ALPHA = 0.95;
const TWL_CONQUEST_HUD_ENGAGE_TRACK_ALPHA = 0.9;
const TWL_CONQUEST_HUD_ENGAGE_FILL_ALPHA = 1;

// Reuse existing shared palette constants rather than duplicating color sources in hud-core.
const TWL_CONQUEST_HUD_COLOR_TRACK = mod.CreateVector(
    CONQUEST_HUD_FLAG_SLOT_TRACK_RGB[0],
    CONQUEST_HUD_FLAG_SLOT_TRACK_RGB[1],
    CONQUEST_HUD_FLAG_SLOT_TRACK_RGB[2]
);
const TWL_CONQUEST_HUD_COLOR_BLUE = mod.CreateVector(
    CONQUEST_HUD_TEXT_FRIENDLY_RGB[0],
    CONQUEST_HUD_TEXT_FRIENDLY_RGB[1],
    CONQUEST_HUD_TEXT_FRIENDLY_RGB[2]
);
const TWL_CONQUEST_HUD_COLOR_RED = mod.CreateVector(
    CONQUEST_HUD_TEXT_ENEMY_RGB[0],
    CONQUEST_HUD_TEXT_ENEMY_RGB[1],
    CONQUEST_HUD_TEXT_ENEMY_RGB[2]
);
const TWL_CONQUEST_HUD_COLOR_WHITE = mod.CreateVector(
    CONQUEST_HUD_TEXT_NEUTRAL_RGB[0],
    CONQUEST_HUD_TEXT_NEUTRAL_RGB[1],
    CONQUEST_HUD_TEXT_NEUTRAL_RGB[2]
);
const TWL_CONQUEST_HUD_COLOR_SHADOW = VEC_ZERO;
const TWL_CONQUEST_HUD_COLOR_BOX_BG = mod.CreateVector(
    CONQUEST_HUD_FLAG_ENGAGE_COUNT_BG_RGB[0],
    CONQUEST_HUD_FLAG_ENGAGE_COUNT_BG_RGB[1],
    CONQUEST_HUD_FLAG_ENGAGE_COUNT_BG_RGB[2]
);
const TWL_CONQUEST_HUD_COLOR_TICKET_BAR_BLUE_TRACK = mod.CreateVector(
    CONQUEST_HUD_TICKET_BAR_FRIENDLY_TRACK_RGB[0],
    CONQUEST_HUD_TICKET_BAR_FRIENDLY_TRACK_RGB[1],
    CONQUEST_HUD_TICKET_BAR_FRIENDLY_TRACK_RGB[2]
);
const TWL_CONQUEST_HUD_COLOR_TICKET_BAR_BLUE_FILL = mod.CreateVector(
    CONQUEST_HUD_TICKET_BAR_FRIENDLY_FILL_RGB[0],
    CONQUEST_HUD_TICKET_BAR_FRIENDLY_FILL_RGB[1],
    CONQUEST_HUD_TICKET_BAR_FRIENDLY_FILL_RGB[2]
);
const TWL_CONQUEST_HUD_COLOR_TICKET_BAR_RED_TRACK = mod.CreateVector(
    CONQUEST_HUD_TICKET_BAR_ENEMY_TRACK_RGB[0],
    CONQUEST_HUD_TICKET_BAR_ENEMY_TRACK_RGB[1],
    CONQUEST_HUD_TICKET_BAR_ENEMY_TRACK_RGB[2]
);
const TWL_CONQUEST_HUD_COLOR_TICKET_BAR_RED_FILL = mod.CreateVector(
    CONQUEST_HUD_TICKET_BAR_ENEMY_FILL_RGB[0],
    CONQUEST_HUD_TICKET_BAR_ENEMY_FILL_RGB[1],
    CONQUEST_HUD_TICKET_BAR_ENEMY_FILL_RGB[2]
);
const TWL_CONQUEST_HUD_COLOR_BLEED_CHEVRON_BLUE = mod.CreateVector(
    CONQUEST_HUD_TICKET_BLEED_CHEVRON_FRIENDLY_RGB[0],
    CONQUEST_HUD_TICKET_BLEED_CHEVRON_FRIENDLY_RGB[1],
    CONQUEST_HUD_TICKET_BLEED_CHEVRON_FRIENDLY_RGB[2]
);
const TWL_CONQUEST_HUD_COLOR_BLEED_CHEVRON_RED = mod.CreateVector(
    CONQUEST_HUD_TICKET_BLEED_CHEVRON_ENEMY_RGB[0],
    CONQUEST_HUD_TICKET_BLEED_CHEVRON_ENEMY_RGB[1],
    CONQUEST_HUD_TICKET_BLEED_CHEVRON_ENEMY_RGB[2]
);
const TWL_CONQUEST_HUD_COLOR_ENGAGE_TRACK = mod.CreateVector(
    CONQUEST_HUD_FLAG_ENGAGE_TRACK_RGB[0],
    CONQUEST_HUD_FLAG_ENGAGE_TRACK_RGB[1],
    CONQUEST_HUD_FLAG_ENGAGE_TRACK_RGB[2]
);

