// @ts-nocheck
// Module: foundation/ui-layout -- HUD, dialog, admin, and victory layout constants

// Clock + HUD layout constants (pixels unless noted).
const TOP_HUD_OFFSET_Y = 10;
// Shared top-stack offsets: keep ticket/flag/engage lanes aligned from one source of truth.
const CONQUEST_HUD_NON_CLOCK_SHIFT_Y = 0;
const CONQUEST_HUD_TICKETS_FLAGS_SHIFT_Y = CONQUEST_HUD_NON_CLOCK_SHIFT_Y + 20;
const CLOCK_POSITION_X = 0;
const CLOCK_POSITION_Y = 45.25;
const CLOCK_WIDTH = 74;
const CLOCK_HEIGHT = 20;
const CLOCK_PLATE_WIDTH = 54;
const CLOCK_PLATE_HEIGHT = 16;
const CLOCK_PLATE_OFFSET_Y = 1;
const CLOCK_PLATE_ALPHA = 0.8;
const ROUND_COUNTER_OFFSET_X = -6;
const ROUND_SLASH_OFFSET_X = -6;
const TOP_HUD_ROOT_WIDTH = 1920;
const TOP_HUD_ROOT_HEIGHT = 260;
const CLOCK_FONT_SIZE = 20;
const CLOCK_TEXT_OFFSET_Y = -1;
const CLOCK_TEXT_SHADOW_OFFSET_X = 0.85;
const CLOCK_TEXT_SHADOW_OFFSET_Y = 0.85;
const CLOCK_TEXT_SHADOW_ALPHA = 0.48;
const CLOCK_DIGIT_LAYOUT_WIDTH = 68;
const CLOCK_DIGIT_INNER_OFFSET_MULT = 0.46;
const CLOCK_DIGIT_OUTER_OFFSET_MULT = 1.16;
const LOW_TIME_THRESHOLD_SECONDS = 5 * 60; // Clock turns team red below 5 minutes remaining.
const CRITICAL_TIME_FLASH_THRESHOLD_SECONDS = 60; // Clock color pulse begins below 1 minute remaining.

// HUD status colors (vectors are RGB 0..1).
const COLOR_NORMAL_RGB: [number, number, number] = [1, 1, 1];
const COLOR_WARNING_YELLOW_RGB: [number, number, number] = [1, 1, 0];
const COLOR_TEAM_RED_RGB: [number, number, number] = [1, 131 / 255, 97 / 255];
const COLOR_NORMAL = mod.CreateVector(COLOR_NORMAL_RGB[0], COLOR_NORMAL_RGB[1], COLOR_NORMAL_RGB[2]);
const COLOR_LOW_TIME = mod.CreateVector(COLOR_TEAM_RED_RGB[0], COLOR_TEAM_RED_RGB[1], COLOR_TEAM_RED_RGB[2]);
const COLOR_READY_GREEN = mod.CreateVector(173 / 255, 253 / 255, 134 / 255); // #ADFD86

// Status / emphasis colors (use constants; do not inline CreateVector() in UI code).
const COLOR_NOT_READY_RED = mod.CreateVector(1, 0, 0);
const COLOR_WARNING_YELLOW = mod.CreateVector(
    COLOR_WARNING_YELLOW_RGB[0],
    COLOR_WARNING_YELLOW_RGB[1],
    COLOR_WARNING_YELLOW_RGB[2]
);

// Conquest HUD color/layout constants (ticket bars + flag row).
// Keep these centralized so ParseUI and runtime updates use one shared palette/geometry contract.
const CONQUEST_HUD_TEXT_FRIENDLY_RGB: [number, number, number] = [112 / 255, 235 / 255, 255 / 255];
const CONQUEST_HUD_TEXT_ENEMY_RGB: [number, number, number] = COLOR_TEAM_RED_RGB;
const CONQUEST_HUD_TEXT_NEUTRAL_RGB: [number, number, number] = [1, 1, 1];
const CONQUEST_HUD_TICKET_BAR_FRIENDLY_TRACK_RGB: [number, number, number] = [19 / 255, 47 / 255, 63 / 255];
const CONQUEST_HUD_TICKET_BAR_ENEMY_TRACK_RGB: [number, number, number] = [64 / 255, 24 / 255, 17 / 255];
const CONQUEST_HUD_TICKET_BAR_FRIENDLY_FILL_RGB: [number, number, number] = [112 / 255, 235 / 255, 255 / 255];
const CONQUEST_HUD_TICKET_BAR_ENEMY_FILL_RGB: [number, number, number] = COLOR_TEAM_RED_RGB;
const CONQUEST_HUD_TICKET_BAR_WIDTH = 173.58;
const CONQUEST_HUD_TICKET_BAR_HEIGHT = 9.60;
const CONQUEST_HUD_TICKET_LEAD_BORDER_GROW = 2;
const CONQUEST_HUD_TICKET_LEAD_BORDER_ALPHA = 1;
const CONQUEST_HUD_TICKET_LEAD_CROWN_SIZE = 20;
const CONQUEST_HUD_TICKET_LEAD_CROWN_GAP_Y = -2;
const CONQUEST_HUD_TICKET_LEAD_CROWN_RGB: [number, number, number] = [1, 252 / 255, 156 / 255];
// Keep ticket counter shadow centered so outline weight is even on all sides.
const CONQUEST_HUD_TICKET_COUNTER_SHADOW_OFFSET = 0;
// Directional ring offset for ticket counter multi-layer shadow widgets.
const CONQUEST_HUD_TICKET_COUNTER_SHADOW_RING_OFFSET = 0.75;
const CONQUEST_HUD_TICKET_COUNTER_SHADOW_ALPHA = 0.45;
const CONQUEST_HUD_TICKET_BLEED_CHEVRON_COUNT = 7;
const CONQUEST_HUD_TICKET_BLEED_CHEVRON_WIDTH = 12;
const CONQUEST_HUD_TICKET_BLEED_CHEVRON_HEIGHT = 10;
const CONQUEST_HUD_TICKET_BLEED_CHEVRON_TEXT_SIZE = 14;
// Use the same bright team colors as ticket fill so chevron cores stay clearly readable.
const CONQUEST_HUD_TICKET_BLEED_CHEVRON_FRIENDLY_RGB: [number, number, number] = CONQUEST_HUD_TICKET_BAR_FRIENDLY_FILL_RGB;
const CONQUEST_HUD_TICKET_BLEED_CHEVRON_ENEMY_RGB: [number, number, number] = CONQUEST_HUD_TICKET_BAR_ENEMY_FILL_RGB;
const CONQUEST_HUD_TICKET_BLEED_CHEVRON_OUTER_INSET_X = 3;
const CONQUEST_HUD_TICKET_BLEED_CHEVRON_IN_BAR_OFFSET_Y = 1;
const CONQUEST_HUD_TICKET_BLEED_CHEVRON_STEP_X = 11;
// Keep chevron shadow tight so the outline reads cleanly without a patchy halo.
const CONQUEST_HUD_TICKET_BLEED_CHEVRON_SHADOW_OFFSET = 1;
const CONQUEST_HUD_TICKET_BLEED_CHEVRON_ANIM_OFF_SECONDS = 0.045;
const CONQUEST_HUD_TICKET_BLEED_CHEVRON_ANIM_ON_SECONDS = 0.055;
const CONQUEST_HUD_TICKET_BAR_LEFT_CENTER_OFFSET_X = 90.67;
const CONQUEST_HUD_TICKET_BAR_RIGHT_CENTER_OFFSET_X = 90.84;
const CONQUEST_HUD_TICKET_BAR_OFFSET_Y = 0;
const CONQUEST_HUD_FLAG_SLOT_WIDTH = 29;
const CONQUEST_HUD_FLAG_SLOT_HEIGHT = 26;
const CONQUEST_HUD_FLAG_FILL_INSET_X = 2;
const CONQUEST_HUD_FLAG_FILL_INSET_Y = 2;
const CONQUEST_HUD_FLAG_FILL_MAX_WIDTH = CONQUEST_HUD_FLAG_SLOT_WIDTH - (CONQUEST_HUD_FLAG_FILL_INSET_X * 2);
const CONQUEST_HUD_FLAG_FILL_MAX_HEIGHT = CONQUEST_HUD_FLAG_SLOT_HEIGHT - (CONQUEST_HUD_FLAG_FILL_INSET_Y * 2);
const CONQUEST_HUD_FLAG_LABEL_WIDGET_GROW = 6;
const CONQUEST_HUD_FLAG_LABEL_WIDGET_WIDTH = CONQUEST_HUD_FLAG_SLOT_WIDTH + CONQUEST_HUD_FLAG_LABEL_WIDGET_GROW;
const CONQUEST_HUD_FLAG_LABEL_WIDGET_HEIGHT = CONQUEST_HUD_FLAG_SLOT_HEIGHT + CONQUEST_HUD_FLAG_LABEL_WIDGET_GROW;
const CONQUEST_HUD_FLAG_LABEL_WIDGET_OFFSET_X = -(CONQUEST_HUD_FLAG_LABEL_WIDGET_GROW / 2);
const CONQUEST_HUD_FLAG_LABEL_WIDGET_OFFSET_Y = -(CONQUEST_HUD_FLAG_LABEL_WIDGET_GROW / 2);
const CONQUEST_HUD_FLAG_LABEL_TEXT_SIZE = 19;
const CONQUEST_HUD_FLAG_LABEL_SHADOW_INNER_TEXT_SIZE = CONQUEST_HUD_FLAG_LABEL_TEXT_SIZE - 3;
const CONQUEST_HUD_FLAG_LABEL_SHADOW_INNER_DEEP_TEXT_SIZE = CONQUEST_HUD_FLAG_LABEL_TEXT_SIZE - 6;
const CONQUEST_HUD_FLAG_LABEL_SHADOW_TEXT_SIZE = CONQUEST_HUD_FLAG_LABEL_TEXT_SIZE;
const CONQUEST_HUD_FLAG_LABEL_SHADOW_OFFSET = 1;
const CONQUEST_HUD_FLAG_PERCENT_ROOT_INSET_X = 1;
const CONQUEST_HUD_FLAG_PERCENT_ROOT_INSET_Y = 1;
const CONQUEST_HUD_FLAG_PERCENT_OFFSET_X = CONQUEST_HUD_FLAG_PERCENT_ROOT_INSET_X;
const CONQUEST_HUD_FLAG_PERCENT_OFFSET_Y = CONQUEST_HUD_FLAG_SLOT_HEIGHT + CONQUEST_HUD_FLAG_PERCENT_ROOT_INSET_Y;
const CONQUEST_HUD_FLAG_PERCENT_ROOT_WIDTH = CONQUEST_HUD_FLAG_SLOT_WIDTH - (CONQUEST_HUD_FLAG_PERCENT_ROOT_INSET_X * 2);
const CONQUEST_HUD_FLAG_PERCENT_ROOT_HEIGHT = 12;
const CONQUEST_HUD_FLAG_PERCENT_WIDGET_GROW = 4;
const CONQUEST_HUD_FLAG_PERCENT_WIDGET_WIDTH = CONQUEST_HUD_FLAG_PERCENT_ROOT_WIDTH + CONQUEST_HUD_FLAG_PERCENT_WIDGET_GROW;
const CONQUEST_HUD_FLAG_PERCENT_WIDGET_HEIGHT = CONQUEST_HUD_FLAG_PERCENT_ROOT_HEIGHT + CONQUEST_HUD_FLAG_PERCENT_WIDGET_GROW;
const CONQUEST_HUD_FLAG_PERCENT_WIDGET_OFFSET_X = -(CONQUEST_HUD_FLAG_PERCENT_WIDGET_GROW / 2);
const CONQUEST_HUD_FLAG_PERCENT_WIDGET_OFFSET_Y = -(CONQUEST_HUD_FLAG_PERCENT_WIDGET_GROW / 2);
const CONQUEST_HUD_FLAG_PERCENT_TEXT_SIZE = Math.max(8, Math.round(CONQUEST_HUD_FLAG_LABEL_TEXT_SIZE * 0.5));
const CONQUEST_HUD_FLAG_PERCENT_SHADOW_OFFSET = 0.5;
const CONQUEST_HUD_FLAG_PERCENT_SHADOW_INNER_TEXT_SIZE = CONQUEST_HUD_FLAG_PERCENT_TEXT_SIZE - 1;
const CONQUEST_HUD_FLAG_PERCENT_SHADOW_TEXT_SIZE = CONQUEST_HUD_FLAG_PERCENT_TEXT_SIZE + 1;
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_ROOT_WIDTH = 64;
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_ROOT_HEIGHT = 64;
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_SLOT_WIDTH = 46;
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_SLOT_HEIGHT = 42;
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_FILL_INSET_X = 3;
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_FILL_INSET_Y = 3;
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_FILL_MAX_WIDTH = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_SLOT_WIDTH - (CONQUEST_HUD_FLAG_ACTIVE_POPOUT_FILL_INSET_X * 2);
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_FILL_MAX_HEIGHT = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_SLOT_HEIGHT - (CONQUEST_HUD_FLAG_ACTIVE_POPOUT_FILL_INSET_Y * 2);
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_SLOT_OFFSET_X = Math.floor((CONQUEST_HUD_FLAG_ACTIVE_POPOUT_ROOT_WIDTH - CONQUEST_HUD_FLAG_ACTIVE_POPOUT_SLOT_WIDTH) / 2);
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_SLOT_OFFSET_Y = 4;
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_LABEL_WIDGET_GROW = 10;
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_LABEL_WIDGET_WIDTH = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_SLOT_WIDTH + CONQUEST_HUD_FLAG_ACTIVE_POPOUT_LABEL_WIDGET_GROW;
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_LABEL_WIDGET_HEIGHT = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_SLOT_HEIGHT + CONQUEST_HUD_FLAG_ACTIVE_POPOUT_LABEL_WIDGET_GROW;
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_LABEL_WIDGET_OFFSET_X = -(CONQUEST_HUD_FLAG_ACTIVE_POPOUT_LABEL_WIDGET_GROW / 2);
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_LABEL_WIDGET_OFFSET_Y = -(CONQUEST_HUD_FLAG_ACTIVE_POPOUT_LABEL_WIDGET_GROW / 2);
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_LABEL_TEXT_SIZE = 27;
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_LABEL_SHADOW_TEXT_SIZE = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_LABEL_TEXT_SIZE;
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_LABEL_SHADOW_OFFSET = 1;
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_OFFSET_X = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_SLOT_OFFSET_X + 4;
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_OFFSET_Y = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_SLOT_OFFSET_Y + CONQUEST_HUD_FLAG_ACTIVE_POPOUT_SLOT_HEIGHT;
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_ROOT_WIDTH = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_SLOT_WIDTH - 8;
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_ROOT_HEIGHT = 16;
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_WIDGET_GROW = 4;
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_WIDGET_WIDTH = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_ROOT_WIDTH + CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_WIDGET_GROW;
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_WIDGET_HEIGHT = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_ROOT_HEIGHT + CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_WIDGET_GROW;
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_WIDGET_OFFSET_X = -(CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_WIDGET_GROW / 2);
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_WIDGET_OFFSET_Y = -(CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_WIDGET_GROW / 2);
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_TEXT_SIZE = 12;
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_SHADOW_TEXT_SIZE = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_TEXT_SIZE + 1;
const CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_SHADOW_INNER_TEXT_SIZE = CONQUEST_HUD_FLAG_ACTIVE_POPOUT_PERCENT_TEXT_SIZE - 1;
const CONQUEST_HUD_FLAG_ENGAGE_ROOT_WIDTH = 152;
const CONQUEST_HUD_FLAG_ENGAGE_ROOT_HEIGHT = 36;
const CONQUEST_HUD_FLAG_ENGAGE_TRACK_WIDTH = 70;
const CONQUEST_HUD_FLAG_ENGAGE_TRACK_X = (CONQUEST_HUD_FLAG_ENGAGE_ROOT_WIDTH - CONQUEST_HUD_FLAG_ENGAGE_TRACK_WIDTH) / 2;
const CONQUEST_HUD_FLAG_ENGAGE_TRACK_Y = 6;
const CONQUEST_HUD_FLAG_ENGAGE_TRACK_HEIGHT = 6;
const CONQUEST_HUD_FLAG_ENGAGE_COUNT_BG_WIDTH = 27;
const CONQUEST_HUD_FLAG_ENGAGE_COUNT_BG_HEIGHT = 16;
const CONQUEST_HUD_FLAG_ENGAGE_COUNT_BG_Y = 1;
const CONQUEST_HUD_FLAG_ENGAGE_COUNT_GAP_X = 1;
const CONQUEST_HUD_FLAG_ENGAGE_FRIENDLY_COUNT_BG_X = CONQUEST_HUD_FLAG_ENGAGE_TRACK_X - CONQUEST_HUD_FLAG_ENGAGE_COUNT_BG_WIDTH - CONQUEST_HUD_FLAG_ENGAGE_COUNT_GAP_X;
const CONQUEST_HUD_FLAG_ENGAGE_ENEMY_COUNT_BG_X = CONQUEST_HUD_FLAG_ENGAGE_TRACK_X + CONQUEST_HUD_FLAG_ENGAGE_TRACK_WIDTH + CONQUEST_HUD_FLAG_ENGAGE_COUNT_GAP_X;
const CONQUEST_HUD_FLAG_ENGAGE_COUNT_TEXT_X = 0;
const CONQUEST_HUD_FLAG_ENGAGE_COUNT_TEXT_Y = 0;
const CONQUEST_HUD_FLAG_ENGAGE_COUNT_SHADOW_OFFSET = 1;
const CONQUEST_HUD_FLAG_ENGAGE_COUNT_TEXT_SIZE = 18;
const CONQUEST_HUD_FLAG_ENGAGE_STATUS_Y = 16;
const CONQUEST_HUD_FLAG_ENGAGE_STATUS_WIDTH = CONQUEST_HUD_FLAG_ENGAGE_ROOT_WIDTH;
const CONQUEST_HUD_FLAG_ENGAGE_STATUS_HEIGHT = 18;
const CONQUEST_HUD_FLAG_ENGAGE_STATUS_TEXT_SIZE = 18;
const CONQUEST_HUD_FLAG_ENGAGE_STATUS_SHADOW_TEXT_SIZE = CONQUEST_HUD_FLAG_ENGAGE_STATUS_TEXT_SIZE;
const CONQUEST_HUD_FLAG_ENGAGE_STATUS_SHADOW_OFFSET = 1;
const CONQUEST_HUD_FLAG_ENGAGE_COUNT_BG_RGB: [number, number, number] = [0.0314, 0.0431, 0.0431];
const CONQUEST_HUD_FLAG_ENGAGE_TRACK_RGB: [number, number, number] = [54 / 255, 57 / 255, 60 / 255];
const CONQUEST_HUD_FLAG_SLOT_TRACK_RGB: [number, number, number] = [54 / 255, 57 / 255, 60 / 255];
const CONQUEST_HUD_FLAG_SLOT_FRIENDLY_FILL_RGB: [number, number, number] = [19 / 255, 47 / 255, 63 / 255];
const CONQUEST_HUD_FLAG_SLOT_ENEMY_FILL_RGB: [number, number, number] = [64 / 255, 24 / 255, 17 / 255];
const CONQUEST_HUD_FLAG_SLOT_CONTEST_BG_RGB: [number, number, number] = [
    CONQUEST_HUD_FLAG_SLOT_TRACK_RGB[0],
    CONQUEST_HUD_FLAG_SLOT_TRACK_RGB[1],
    CONQUEST_HUD_FLAG_SLOT_TRACK_RGB[2],
];
const CONQUEST_HUD_FLAG_LABEL_OWNED_RGB: [number, number, number] = [1, 1, 1];
const CONQUEST_HUD_FLAG_LABEL_NEUTRAL_RGB: [number, number, number] = [1, 1, 1];
const CONQUEST_HUD_FLAG_LABEL_ACTIVE_RGB: [number, number, number] = [0, 0, 0];
const CLOCK_COLON_OFFSET_X = -4;

// Buttons look and feel (base / selected / pressed / border).
const COLOR_BUTTON_BASE = COLOR_GRAY;
const BUTTON_OPACITY_BASE = 0.75;
const COLOR_BUTTON_SELECTED = COLOR_BLUE;
const BUTTON_OPACITY_SELECTED = 0.75;
const COLOR_BUTTON_PRESSED = COLOR_WHITE;
const BUTTON_OPACITY_PRESSED = 0.75;
const COLOR_BUTTON_BORDER = COLOR_GRAY;
const BUTTON_BORDER_OPACITY = 0.50;
const BUTTON_BORDER_PADDING = 0;

// Ready Dialog
const READY_DIALOG_SMALL_BUTTON_WIDTH = 26;
const READY_DIALOG_SMALL_BUTTON_HEIGHT = 24;
const READY_DIALOG_MAIN_BUTTON_WIDTH = 300;
const READY_DIALOG_MAIN_BUTTON_HEIGHT = 45;
// Ready button horizontal offset relative to dialog center.
const READY_DIALOG_READY_BUTTON_OFFSET_X = -(Math.floor(READY_DIALOG_MAIN_BUTTON_WIDTH / 2) + 10);
const READY_DIALOG_COACH_BUTTON_OFFSET_X = (Math.floor(READY_DIALOG_MAIN_BUTTON_WIDTH / 2) + 10);
const READY_DIALOG_CONFIRM_BUTTON_GAP = 8;
const READY_DIALOG_CONFIRM_BUTTON_WIDTH = 170;
const READY_DIALOG_RESET_BUTTON_WIDTH = READY_DIALOG_CONFIRM_BUTTON_WIDTH;
const READY_DIALOG_RESET_BUTTON_OFFSET_X = 0;
const READY_DIALOG_CONTAINER_WIDTH = 1300;
const READY_DIALOG_CONTENT_LANE_WIDTH = 1200;
const READY_DIALOG_CONTENT_OFFSET_X = -10;
const READY_DIALOG_ROSTER_VISUAL_OFFSET_X = 0;
const READY_PANEL_T1_BG_COLOR = mod.CreateVector(0.10, 0.25, 0.70);
const READY_PANEL_T2_BG_COLOR = mod.CreateVector(0.70, 0.15, 0.15);
const READY_PANEL_BG_ALPHA = 0.20;
const READY_DIALOG_BUTTON_TEXT_COLOR_RGB: [number, number, number] = [1, 1, 1];
const READY_DIALOG_LABEL_TEXT_COLOR = COLOR_WHITE;
const READY_DIALOG_BORDER_COLOR = COLOR_GRAY;
const HUD_WARM_PREBUILD_DELAY_SECONDS = 0.01;
const HUD_WARM_REDEPLOY_BLOCK_SECONDS = 999;
const HUD_WARM_READY_POLL_SECONDS = 0.05;
const HUD_WARM_READY_STABLE_POLLS = 1;
const HUD_WARM_READY_TIMEOUT_SECONDS = 2.5;

// Admin Panel
const ADMIN_PANEL_HEIGHT = 290;
const ADMIN_PANEL_PADDING = 5;
const ADMIN_PANEL_BASE_X = -5;
const ADMIN_PANEL_BASE_Y = 15;
const ADMIN_PANEL_OFFSET_X = 10;
const ADMIN_PANEL_OFFSET_Y = 15;
const ADMIN_PANEL_TOGGLE_OFFSET_X = 10;
const ADMIN_PANEL_TOGGLE_OFFSET_Y = 15;
const ADMIN_PANEL_TOGGLE_WIDTH = 120;
const ADMIN_PANEL_TOGGLE_HEIGHT = 24;
const ADMIN_PANEL_BUTTON_SIZE_X = 48;
const ADMIN_PANEL_BUTTON_SIZE_Y = 30;
const ADMIN_PANEL_LABEL_SIZE_X = 130;
const ADMIN_PANEL_CONTENT_WIDTH = (ADMIN_PANEL_BUTTON_SIZE_X * 2) + ADMIN_PANEL_LABEL_SIZE_X + 16;
const ADMIN_PANEL_ROW_SPACING_Y = 4;
const ADMIN_PANEL_BG_COLOR = COLOR_DARK_BLACK;
const ADMIN_PANEL_BG_ALPHA = 1.0;
const ADMIN_PANEL_BG_FILL = mod.UIBgFill.Blur;
const ADMIN_PANEL_LABEL_TEXT_COLOR_RGB: [number, number, number] = [1, 1, 1];
const ADMIN_PANEL_BUTTON_TEXT_COLOR = COLOR_WHITE;
const ADMIN_PANEL_LABEL_TEXT_COLOR = COLOR_WHITE;

// Vehicle deploy timer HUD (Phase 5B first pass).
const VEHICLE_DEPLOY_TIMER_ROOT_OFFSET_X = 12;
// Preserve the original lower anchor line from the 4-row layout and grow upward from there.
const VEHICLE_DEPLOY_TIMER_ROOT_OFFSET_Y = -187;
const VEHICLE_DEPLOY_TIMER_ROOT_WIDTH = 486;
const VEHICLE_DEPLOY_TIMER_CONTENT_HEIGHT = 394;
const VEHICLE_DEPLOY_TIMER_ROOT_HEIGHT = 432;
const VEHICLE_DEPLOY_TIMER_ROW_HEIGHT = 30;
const VEHICLE_DEPLOY_TIMER_ROW_GAP_Y = 2;
const VEHICLE_DEPLOY_TIMER_PLAYER_PLATE_X = 0;
const VEHICLE_DEPLOY_TIMER_PLAYER_PLATE_WIDTH = 176;
const VEHICLE_DEPLOY_TIMER_ROW_GAP_X = 6;
const VEHICLE_DEPLOY_TIMER_SPAWN_BUTTON_X = VEHICLE_DEPLOY_TIMER_PLAYER_PLATE_X + VEHICLE_DEPLOY_TIMER_PLAYER_PLATE_WIDTH + VEHICLE_DEPLOY_TIMER_ROW_GAP_X;
const VEHICLE_DEPLOY_TIMER_SPAWN_BUTTON_WIDTH = 92;
const VEHICLE_DEPLOY_TIMER_SPAWN_BUTTON_HEIGHT = 20;
const VEHICLE_DEPLOY_TIMER_SPAWN_BUTTON_OFFSET_Y = -1;
const VEHICLE_DEPLOY_TIMER_VEHICLE_PLATE_X = VEHICLE_DEPLOY_TIMER_SPAWN_BUTTON_X + VEHICLE_DEPLOY_TIMER_SPAWN_BUTTON_WIDTH + VEHICLE_DEPLOY_TIMER_ROW_GAP_X;
const VEHICLE_DEPLOY_TIMER_VEHICLE_PLATE_WIDTH = 136;
const VEHICLE_DEPLOY_TIMER_TIMER_X = VEHICLE_DEPLOY_TIMER_VEHICLE_PLATE_X + VEHICLE_DEPLOY_TIMER_VEHICLE_PLATE_WIDTH + VEHICLE_DEPLOY_TIMER_ROW_GAP_X;
const VEHICLE_DEPLOY_TIMER_TIMER_Y = 0;
const VEHICLE_DEPLOY_TIMER_MAX_ROWS = 12;
const VEHICLE_DEPLOY_TIMER_WIDTH = 54;
const VEHICLE_DEPLOY_TIMER_HEIGHT = 18;
const VEHICLE_DEPLOY_TIMER_PLATE_WIDTH = 54;
const VEHICLE_DEPLOY_TIMER_PLATE_HEIGHT = 16;
const VEHICLE_DEPLOY_TIMER_PLATE_OFFSET_Y = 0;
const VEHICLE_DEPLOY_TIMER_FONT_SIZE = 15;
const VEHICLE_DEPLOY_TIMER_TEXT_OFFSET_Y = -1;
const VEHICLE_DEPLOY_TIMER_TEXT_SHADOW_OFFSET_X = 0.75;
const VEHICLE_DEPLOY_TIMER_TEXT_SHADOW_OFFSET_Y = 0.75;
const VEHICLE_DEPLOY_TIMER_TEXT_SHADOW_ALPHA = 0.42;
const VEHICLE_DEPLOY_TIMER_DIGIT_LAYOUT_WIDTH = 44;
const VEHICLE_DEPLOY_TIMER_DIGIT_INNER_OFFSET_MULT = 0.46;
const VEHICLE_DEPLOY_TIMER_DIGIT_OUTER_OFFSET_MULT = 1.14;
const VEHICLE_DEPLOY_TIMER_COLON_OFFSET_X = -5;
const VEHICLE_DEPLOY_TIMER_COLON_OFFSET_Y = -1;
const VEHICLE_DEPLOY_TIMER_MINUTE_DIGIT_OFFSET_X = 3;
const VEHICLE_DEPLOY_TIMER_SECOND_DIGIT_OFFSET_X = 1;
const VEHICLE_DEPLOY_TIMER_INFO_PLATE_HEIGHT = 18;
const VEHICLE_DEPLOY_TIMER_INFO_TEXT_SIZE = 12;
const VEHICLE_DEPLOY_TIMER_INFO_TEXT_SHADOW_OFFSET_X = 0.75;
const VEHICLE_DEPLOY_TIMER_INFO_TEXT_SHADOW_OFFSET_Y = 0.75;
const VEHICLE_DEPLOY_TIMER_INFO_TEXT_SHADOW_ALPHA = 0.42;
const VEHICLE_DEPLOY_TIMER_SPAWN_BUTTON_BORDER_PADDING = 1;
const VEHICLE_DEPLOY_TIMER_SPAWN_BUTTON_TEXT_SIZE = 12;
const VEHICLE_DEPLOY_TIMER_SPAWN_BUTTON_BG_ALPHA = 1;
const VEHICLE_DEPLOY_TIMER_SPAWN_BUTTON_PADDING_BASE = 1;
const VEHICLE_DEPLOY_TIMER_SPAWN_BUTTON_PADDING_HOVER = 1;
const VEHICLE_DEPLOY_TIMER_SPAWN_BUTTON_PADDING_PRESSED = 1;
const VEHICLE_DEPLOY_TIMER_SPAWN_BUTTON_BLUR_ALPHA = 0.55;
const VEHICLE_DEPLOY_TIMER_GROUND_BUTTON_X = VEHICLE_DEPLOY_TIMER_SPAWN_BUTTON_X - VEHICLE_DEPLOY_TIMER_ROW_GAP_X - VEHICLE_DEPLOY_TIMER_SPAWN_BUTTON_WIDTH;
const VEHICLE_DEPLOY_TIMER_LIVE_PANEL_X = VEHICLE_DEPLOY_TIMER_GROUND_BUTTON_X - 6;
const VEHICLE_DEPLOY_TIMER_LIVE_PANEL_Y = 0;
const VEHICLE_DEPLOY_TIMER_LIVE_PANEL_WIDTH = VEHICLE_DEPLOY_TIMER_ROOT_WIDTH - VEHICLE_DEPLOY_TIMER_LIVE_PANEL_X;
const VEHICLE_DEPLOY_TIMER_LIVE_PANEL_HEIGHT = VEHICLE_DEPLOY_TIMER_ROOT_HEIGHT;
const VEHICLE_DEPLOY_TIMER_CLOSE_BUTTON_WIDTH = 132;
const VEHICLE_DEPLOY_TIMER_CLOSE_BUTTON_X = VEHICLE_DEPLOY_TIMER_LIVE_PANEL_X + Math.floor((VEHICLE_DEPLOY_TIMER_LIVE_PANEL_WIDTH - VEHICLE_DEPLOY_TIMER_CLOSE_BUTTON_WIDTH) / 2);
const VEHICLE_DEPLOY_TIMER_CLOSE_BUTTON_Y = VEHICLE_DEPLOY_TIMER_CONTENT_HEIGHT + 8;
const VEHICLE_DEPLOY_TIMER_CLOSE_BUTTON_HEIGHT = 20;
const VEHICLE_DEPLOY_TIMER_LIVE_PANEL_BG_COLOR = mod.CreateVector(56 / 255, 8 / 255, 8 / 255);
const VEHICLE_DEPLOY_TIMER_LIVE_PANEL_BG_ALPHA = 0.56;

// Victory dialog theme colors (ParseUI expects RGB tuples, not vectors).
const VICTORY_BG_RGB: [number, number, number] = [0.0314, 0.0431, 0.0431];
const VICTORY_TEAM1_BG_RGB: [number, number, number] = [0.1098, 0.2304, 0.25];
const VICTORY_TEAM2_BG_RGB: [number, number, number] = [0.25, 0.1284, 0.0951];
const VICTORY_TEAM1_TEXT_RGB: [number, number, number] = [0.4392, 0.9216, 1];
const VICTORY_TEAM2_TEXT_RGB: [number, number, number] = [1, 0.5137, 0.3804];
const VICTORY_DIALOG_WIDTH = 360;
const VICTORY_DIALOG_HEIGHT = 500;
const VICTORY_DIALOG_ROSTER_ROW_Y = 282;
const VICTORY_DIALOG_ROSTER_ROW_WIDTH = 340;
const VICTORY_DIALOG_ROSTER_ROW_HEIGHT_MAX = 200;
const VICTORY_DIALOG_ROSTER_CONTAINER_WIDTH = 160;
const VICTORY_DIALOG_ROSTER_ROW_HEIGHT = 12;
const VICTORY_DIALOG_ROSTER_ROW_PADDING_TOP = 4;
const VICTORY_DIALOG_ROSTER_ROW_PADDING_BOTTOM = 4;
const VICTORY_DIALOG_BOTTOM_PADDING = 18;
