// @ts-nocheck
// Module: strings/ui-ids -- widget id constants and string key policy notes

//#region ----------------- String Variables --------------------

// -------------------- Strings.json key policy --------------------
//
// - UI labels (static text) should be shared (e.g., a single shared label key) rather than duplicated per team.
// - Per-team differences belong in layout/widget placement, not in duplicated label strings.
// - Dynamic values (numbers) are usually written into value widgets directly; avoid creating many one-off strings.
// - If you must use placeholders, keep formatting consistent across the file.
// - Reminder: UI widget `name:` values are NOT Strings.json keys; they are runtime widget IDs.
//
// Policy compliance checklist:
// - New UI text added? Put it in Strings.json under a shared key (no per-team duplication).
// - Using placeholders? Match existing formatting patterns for that section.
// - Reusing an existing label? Use the existing string key rather than a new alias.
// - Avoid creating string key constants unless reused in multiple places.
//
// ------------------------------------------------------------------

// UI widget ID constants (string prefixes used to find widgets).
// All UI widget IDs are per-player; the viewer's pid is appended at use sites.
const UI_READY_DIALOG_CONTAINER_BASE_ID = "UI_READY_DIALOG_CONTAINER_BASE_";
const UI_READY_DIALOG_BORDER_TOP_ID = "UI_READY_DIALOG_BORDER_TOP_";
const UI_READY_DIALOG_BORDER_BOTTOM_ID = "UI_READY_DIALOG_BORDER_BOTTOM_";
const UI_READY_DIALOG_BORDER_LEFT_ID = "UI_READY_DIALOG_BORDER_LEFT_";
const UI_READY_DIALOG_BORDER_RIGHT_ID = "UI_READY_DIALOG_BORDER_RIGHT_";
const UI_READY_DIALOG_BUTTON_CANCEL_ID = "UI_READY_DIALOG_BUTTON_CANCEL_";
const UI_READY_DIALOG_BUTTON_CANCEL_LABEL_ID = "UI_READY_DIALOG_BUTTON_CANCEL_LABEL_";

// Ready Dialog (Roster UI) - Widget ID bases (per-player IDs append viewer playerId).
const UI_READY_DIALOG_HEADER_ID = "UI_READY_DIALOG_HEADER_";
const UI_READY_DIALOG_HEADER2_ID = "UI_READY_DIALOG_HEADER2_";
const UI_READY_DIALOG_HEADER3_ID = "UI_READY_DIALOG_HEADER3_";
const UI_READY_DIALOG_HEADER4_ID = "UI_READY_DIALOG_HEADER4_";
const UI_READY_DIALOG_HEADER5_ID = "UI_READY_DIALOG_HEADER5_";
const UI_READY_DIALOG_HEADER6_ID = "UI_READY_DIALOG_HEADER6_";
const UI_READY_DIALOG_TEAM1_CONTAINER_ID = "UI_READY_DIALOG_TEAM1_CONTAINER_";
const UI_READY_DIALOG_TEAM2_CONTAINER_ID = "UI_READY_DIALOG_TEAM2_CONTAINER_";
const UI_READY_DIALOG_TEAM1_LABEL_ID = "UI_READY_DIALOG_TEAM1_LABEL_";
const UI_READY_DIALOG_TEAM2_LABEL_ID = "UI_READY_DIALOG_TEAM2_LABEL_";
const UI_READY_DIALOG_T1_ROW_NAME_ID = "UI_READY_DIALOG_T1_ROW_NAME_";
const UI_READY_DIALOG_T1_ROW_READY_ID = "UI_READY_DIALOG_T1_ROW_READY_";
const UI_READY_DIALOG_T1_ROW_BASE_ID = "UI_READY_DIALOG_T1_ROW_BASE_";
const UI_READY_DIALOG_T2_ROW_NAME_ID = "UI_READY_DIALOG_T2_ROW_NAME_";
const UI_READY_DIALOG_T2_ROW_READY_ID = "UI_READY_DIALOG_T2_ROW_READY_";
const UI_READY_DIALOG_T2_ROW_BASE_ID = "UI_READY_DIALOG_T2_ROW_BASE_";
const UI_READY_DIALOG_BUTTON_READY_ID = "UI_READY_DIALOG_BUTTON_READY_";
const UI_READY_DIALOG_BUTTON_READY_LABEL_ID = "UI_READY_DIALOG_BUTTON_READY_LABEL_";
const UI_READY_DIALOG_BUTTON_COACH_ID = "UI_READY_DIALOG_BUTTON_COACH_";
const UI_READY_DIALOG_BUTTON_COACH_LABEL_ID = "UI_READY_DIALOG_BUTTON_COACH_LABEL_";
const UI_READY_DIALOG_BUTTON_SWAP_ID = "UI_READY_DIALOG_BUTTON_SWAP_";
const UI_READY_DIALOG_BUTTON_SWAP_LABEL_ID = "UI_READY_DIALOG_BUTTON_SWAP_LABEL_";
const UI_READY_DIALOG_MAP_LABEL_ID = "UI_READY_DIALOG_MAP_LABEL_";
const UI_READY_DIALOG_MAP_VALUE_ID = "UI_READY_DIALOG_MAP_VALUE_";
const UI_READY_DIALOG_MODE_CONFIRM_ID = "UI_READY_DIALOG_MODE_CONFIRM_";
const UI_READY_DIALOG_MODE_CONFIRM_LABEL_ID = "UI_READY_DIALOG_MODE_CONFIRM_LABEL_";
const UI_READY_DIALOG_MODE_RESET_ID = "UI_READY_DIALOG_MODE_RESET_";
const UI_READY_DIALOG_MODE_RESET_LABEL_ID = "UI_READY_DIALOG_MODE_RESET_LABEL_";
const UI_READY_DIALOG_MODE_UNSAVED_LABEL_ID = "UI_READY_DIALOG_MODE_UNSAVED_LABEL_";
const UI_READY_DIALOG_MODE_GRID_COLUMN_HEADER_ID = "UI_READY_DIALOG_MODE_GRID_COLUMN_HEADER_";
const UI_READY_DIALOG_MODE_GRID_KNOB_LABEL_ID = "UI_READY_DIALOG_MODE_GRID_KNOB_LABEL_";
const UI_READY_DIALOG_MODE_GRID_KNOB_VALUE_ID = "UI_READY_DIALOG_MODE_GRID_KNOB_VALUE_";
const UI_READY_DIALOG_MODE_GRID_KNOB_PANEL_ID = "UI_READY_DIALOG_MODE_GRID_KNOB_PANEL_";
const UI_READY_DIALOG_MODE_GRID_KNOB_DEC_ID = "UI_READY_DIALOG_MODE_GRID_KNOB_DEC_";
const UI_READY_DIALOG_MODE_GRID_KNOB_DEC_LABEL_ID = "UI_READY_DIALOG_MODE_GRID_KNOB_DEC_LABEL_";
const UI_READY_DIALOG_MODE_GRID_KNOB_INC_ID = "UI_READY_DIALOG_MODE_GRID_KNOB_INC_";
const UI_READY_DIALOG_MODE_GRID_KNOB_INC_LABEL_ID = "UI_READY_DIALOG_MODE_GRID_KNOB_INC_LABEL_";
const UI_READY_DIALOG_MODE_GRID_SUPPORT_ID = "UI_READY_DIALOG_MODE_GRID_SUPPORT_";

// Admin/Tester UI - Widget ID bases (per-player IDs append viewer playerId).
const UI_TEST_HEADER_LABEL_ID = "UI_TEST_HEADER_LABEL_";
const UI_TEST_BUTTON_CLOCK_TIME_DEC_ID = "UI_TEST_BUTTON_CLOCK_TIME_DEC_";
const UI_TEST_BUTTON_CLOCK_TIME_INC_ID = "UI_TEST_BUTTON_CLOCK_TIME_INC_";
const UI_TEST_BUTTON_CLOCK_RESET_ID = "UI_TEST_BUTTON_CLOCK_RESET_";
const UI_TEST_BUTTON_MATCH_START_ID = "UI_TEST_BUTTON_MATCH_START_";
const UI_TEST_BUTTON_MATCH_END_ID = "UI_TEST_BUTTON_MATCH_END_";
const UI_TEST_BUTTON_POS_DEBUG_ID = "UI_TEST_BUTTON_POS_DEBUG_";
const UI_TEST_BUTTON_DEPLOY_TIMERS_TOGGLE_ID = "UI_TEST_BUTTON_DEPLOY_TIMERS_TOGGLE_";
const UI_TEST_BUTTON_RESET_GADGET_TIMERS_ID = "UI_TEST_BUTTON_RESET_GADGET_TIMERS_";
const UI_TEST_BUTTON_UI_CACHE_PERF_TOGGLE_ID = "UI_TEST_BUTTON_UI_CACHE_PERF_TOGGLE_";
const UI_TEST_BUTTON_PERF_DIAG_TOGGLE_ID = "UI_TEST_BUTTON_PERF_DIAG_TOGGLE_";
const UI_TEST_BUTTON_GROUND_DEPLOY_ALL_ID = "UI_TEST_BUTTON_GROUND_DEPLOY_ALL_";
const UI_TEST_LABEL_CLOCK_TIME_ID = "UI_TEST_LABEL_CLOCK_TIME_";
const UI_TEST_PLUS_TEXT_ID = "UI_TEST_PLUS_TEXT_";
const UI_TEST_MINUS_TEXT_ID = "UI_TEST_MINUS_TEXT_";
const UI_TEST_RESET_TEXT_ID = "UI_TEST_RESET_TEXT_";
const UI_TEST_MATCH_START_TEXT_ID = "UI_TEST_MATCH_START_TEXT_";
const UI_TEST_MATCH_END_TEXT_ID = "UI_TEST_MATCH_END_TEXT_";
const UI_TEST_POS_DEBUG_TEXT_ID = "UI_TEST_POS_DEBUG_TEXT_";
const UI_TEST_DEPLOY_TIMERS_TOGGLE_TEXT_ID = "UI_TEST_DEPLOY_TIMERS_TOGGLE_TEXT_";
const UI_TEST_RESET_GADGET_TIMERS_TEXT_ID = "UI_TEST_RESET_GADGET_TIMERS_TEXT_";
const UI_TEST_UI_CACHE_PERF_TOGGLE_TEXT_ID = "UI_TEST_UI_CACHE_PERF_TOGGLE_TEXT_";
const UI_TEST_PERF_DIAG_TOGGLE_TEXT_ID = "UI_TEST_PERF_DIAG_TOGGLE_TEXT_";
const UI_TEST_GROUND_DEPLOY_ALL_TEXT_ID = "UI_TEST_GROUND_DEPLOY_ALL_TEXT_";
// Test Minimal Spawn — isolated spawn+teleport+seat pattern (v1.235 diagnostic, Phase 1 of vehicle deploy recovery plan)
const UI_TEST_BUTTON_MIN_SPAWN_F16_ID = "UI_TEST_BUTTON_MIN_SPAWN_F16_";
const UI_TEST_BUTTON_MIN_SPAWN_AH64_ID = "UI_TEST_BUTTON_MIN_SPAWN_AH64_";
const UI_TEST_BUTTON_MIN_SPAWN_F22_ID = "UI_TEST_BUTTON_MIN_SPAWN_F22_";
const UI_TEST_BUTTON_MIN_SPAWN_MH6_ID = "UI_TEST_BUTTON_MIN_SPAWN_MH6_";
const UI_TEST_BUTTON_MIN_SPAWN_ABRAMS_ID = "UI_TEST_BUTTON_MIN_SPAWN_ABRAMS_";
const UI_TEST_MIN_SPAWN_F16_TEXT_ID = "UI_TEST_MIN_SPAWN_F16_TEXT_";
const UI_TEST_MIN_SPAWN_AH64_TEXT_ID = "UI_TEST_MIN_SPAWN_AH64_TEXT_";
const UI_TEST_MIN_SPAWN_F22_TEXT_ID = "UI_TEST_MIN_SPAWN_F22_TEXT_";
const UI_TEST_MIN_SPAWN_MH6_TEXT_ID = "UI_TEST_MIN_SPAWN_MH6_TEXT_";
const UI_TEST_MIN_SPAWN_ABRAMS_TEXT_ID = "UI_TEST_MIN_SPAWN_ABRAMS_TEXT_";
const UI_TEST_BUTTON_MIN_SPAWN_SPWN_ID = "UI_TEST_BUTTON_MIN_SPAWN_SPWN_";
const UI_TEST_MIN_SPAWN_SPWN_TEXT_ID = "UI_TEST_MIN_SPAWN_SPWN_TEXT_";
// Deploy diagnostic HUD (v1.239 Phase 1 Part A — defined inside src/hud/deploy-diagnostic.ts
// to let the FEATURE_DEPLOY_DIAGNOSTIC=false dead-code elimination strip the constants along
// with the module; rip all with the twl.deployDiag.* strings when done)
// BountyHunter isolated spawn test buttons (v1.246 diagnostic)
const UI_TEST_BUTTON_BH_F16_ID = "UI_TEST_BUTTON_BH_F16_";
const UI_TEST_BUTTON_BH_AH6M_ID = "UI_TEST_BUTTON_BH_AH6M_";
const UI_TEST_BUTTON_BH_DIRTBIKE_ID = "UI_TEST_BUTTON_BH_DIRTBIKE_";
const UI_TEST_BUTTON_BH_BLACKHAWK_ID = "UI_TEST_BUTTON_BH_BLACKHAWK_";
const UI_TEST_BH_F16_TEXT_ID = "UI_TEST_BH_F16_TEXT_";
const UI_TEST_BH_AH6M_TEXT_ID = "UI_TEST_BH_AH6M_TEXT_";
const UI_TEST_BH_DIRTBIKE_TEXT_ID = "UI_TEST_BH_DIRTBIKE_TEXT_";
const UI_TEST_BH_BLACKHAWK_TEXT_ID = "UI_TEST_BH_BLACKHAWK_TEXT_";
const UI_ADMIN_MATCH_LENGTH_DEC_ID = "UI_ADMIN_MATCH_LENGTH_DEC_";
const UI_ADMIN_MATCH_LENGTH_INC_ID = "UI_ADMIN_MATCH_LENGTH_INC_";
const UI_ADMIN_MATCH_LENGTH_LABEL_ID = "UI_ADMIN_MATCH_LENGTH_LABEL_";
const UI_VEHICLE_DEPLOY_TIMER_SPAWN_BUTTON_ID = "UI_VEHICLE_DEPLOY_TIMER_SPAWN_BUTTON_";
const UI_VEHICLE_DEPLOY_TIMER_GROUND_BUTTON_ID = "UI_VEHICLE_DEPLOY_TIMER_GROUND_BUTTON_";

// Debug Positioning UI
const UI_POS_DEBUG_CONTAINER_ID = "UI_POS_DEBUG_CONTAINER_";
const UI_PERF_DIAG_CONTAINER_ID = "UI_PERF_DIAG_CONTAINER_";
const UI_PERF_DIAG_HEADER_ID = "UI_PERF_DIAG_HEADER_";
const UI_PERF_DIAG_SECTION_ID = "UI_PERF_DIAG_S_";
const UI_POS_DEBUG_X_ID = "UI_POS_DEBUG_X_";
const UI_POS_DEBUG_Y_ID = "UI_POS_DEBUG_Y_";
const UI_POS_DEBUG_Z_ID = "UI_POS_DEBUG_Z_";
const UI_POS_DEBUG_X_VALUE_ID = "UI_POS_DEBUG_X_VALUE_";
const UI_POS_DEBUG_Y_VALUE_ID = "UI_POS_DEBUG_Y_VALUE_";
const UI_POS_DEBUG_Z_VALUE_ID = "UI_POS_DEBUG_Z_VALUE_";
const UI_POS_DEBUG_ROTX_ID = "UI_POS_DEBUG_ROTX_";
const UI_POS_DEBUG_ROTY_ID = "UI_POS_DEBUG_ROTY_";
const UI_POS_DEBUG_ROTZ_ID = "UI_POS_DEBUG_ROTZ_";
const UI_POS_DEBUG_ROTX_VALUE_ID = "UI_POS_DEBUG_ROTX_VALUE_";
const UI_POS_DEBUG_ROTY_VALUE_ID = "UI_POS_DEBUG_ROTY_VALUE_";
const UI_POS_DEBUG_ROTZ_VALUE_ID = "UI_POS_DEBUG_ROTZ_VALUE_";

// HUD Team Swap Button (pre-game only, top HUD right side)
const UI_HUD_TEAM_SWAP_BUTTON_ID = "UI_HUD_TEAM_SWAP_";
const UI_HUD_TEAM_SWAP_LABEL_ID = "UI_HUD_TEAM_SWAP_LABEL_";

// Admin Panel (decoupled from main Ready Dialog)
const UI_ADMIN_PANEL_BUTTON_ID = "UI_ADMIN_PANEL_BUTTON_";
const UI_ADMIN_PANEL_BUTTON_LABEL_ID = "UI_ADMIN_PANEL_BUTTON_LABEL_";
const UI_ADMIN_PANEL_CONTAINER_ID = "UI_ADMIN_PANEL_CONTAINER_";

//#endregion -------------- String Variables --------------------

