// @ts-nocheck
// Module: strings/ui-ids -- widget id constants and string key policy notes

//#region ----------------- String Variables --------------------

// -------------------- Strings.json key policy --------------------
//
// - UI labels (static text) should be shared (e.g., a single shared label key) rather than duplicated per team.
// - Per-team differences belong in layout/widget placement, not in duplicated label strings.
// - Dynamic values (numbers) are usually written into value widgets directly; avoid creating many one-off strings.
// - If you must use placeholders, keep formatting consistent across the file.
// - Reminder: UI widget `name:` values are NOT Strings.json keys; they are runtime widget IDs.
//
// Policy compliance checklist:
// - New UI text added? Put it in Strings.json under a shared key (no per-team duplication).
// - Using placeholders? Match existing formatting patterns for that section.
// - Reusing an existing label? Use the existing string key rather than a new alias.
// - Avoid creating string key constants unless reused in multiple places.
//
// ------------------------------------------------------------------

// UI widget ID constants (string prefixes used to find widgets).
// All UI widget IDs are per-player; the viewer's pid is appended at use sites.
const UI_READY_DIALOG_CONTAINER_BASE_ID = "UI_READY_DIALOG_CONTAINER_BASE_";
const UI_READY_DIALOG_BORDER_TOP_ID = "UI_READY_DIALOG_BORDER_TOP_";
const UI_READY_DIALOG_BORDER_BOTTOM_ID = "UI_READY_DIALOG_BORDER_BOTTOM_";
const UI_READY_DIALOG_BORDER_LEFT_ID = "UI_READY_DIALOG_BORDER_LEFT_";
const UI_READY_DIALOG_BORDER_RIGHT_ID = "UI_READY_DIALOG_BORDER_RIGHT_";
const UI_READY_DIALOG_BUTTON_CANCEL_ID = "UI_READY_DIALOG_BUTTON_CANCEL_";
const UI_READY_DIALOG_BUTTON_CANCEL_LABEL_ID = "UI_READY_DIALOG_BUTTON_CANCEL_LABEL_";
const UI_READY_DIALOG_DEBUG_TIMELIMIT_ID = "UI_READY_DIALOG_DEBUG_TIMELIMIT_";

// Ready Dialog (Roster UI) - Widget ID bases (per-player IDs append viewer playerId).
const UI_READY_DIALOG_HEADER_ID = "UI_READY_DIALOG_HEADER_";
const UI_READY_DIALOG_HEADER2_ID = "UI_READY_DIALOG_HEADER2_";
const UI_READY_DIALOG_HEADER3_ID = "UI_READY_DIALOG_HEADER3_";
const UI_READY_DIALOG_HEADER4_ID = "UI_READY_DIALOG_HEADER4_";
const UI_READY_DIALOG_HEADER5_ID = "UI_READY_DIALOG_HEADER5_";
const UI_READY_DIALOG_HEADER6_ID = "UI_READY_DIALOG_HEADER6_";
const UI_READY_DIALOG_TEAM1_CONTAINER_ID = "UI_READY_DIALOG_TEAM1_CONTAINER_";
const UI_READY_DIALOG_TEAM2_CONTAINER_ID = "UI_READY_DIALOG_TEAM2_CONTAINER_";
const UI_READY_DIALOG_TEAM1_LABEL_ID = "UI_READY_DIALOG_TEAM1_LABEL_";
const UI_READY_DIALOG_TEAM2_LABEL_ID = "UI_READY_DIALOG_TEAM2_LABEL_";
const UI_READY_DIALOG_T1_ROW_NAME_ID = "UI_READY_DIALOG_T1_ROW_NAME_";
const UI_READY_DIALOG_T1_ROW_READY_ID = "UI_READY_DIALOG_T1_ROW_READY_";
const UI_READY_DIALOG_T1_ROW_BASE_ID = "UI_READY_DIALOG_T1_ROW_BASE_";
const UI_READY_DIALOG_T2_ROW_NAME_ID = "UI_READY_DIALOG_T2_ROW_NAME_";
const UI_READY_DIALOG_T2_ROW_READY_ID = "UI_READY_DIALOG_T2_ROW_READY_";
const UI_READY_DIALOG_T2_ROW_BASE_ID = "UI_READY_DIALOG_T2_ROW_BASE_";
const UI_READY_DIALOG_BUTTON_READY_ID = "UI_READY_DIALOG_BUTTON_READY_";
const UI_READY_DIALOG_BUTTON_READY_LABEL_ID = "UI_READY_DIALOG_BUTTON_READY_LABEL_";
const UI_READY_DIALOG_BUTTON_SWAP_ID = "UI_READY_DIALOG_BUTTON_SWAP_";
const UI_READY_DIALOG_BUTTON_SWAP_LABEL_ID = "UI_READY_DIALOG_BUTTON_SWAP_LABEL_";
const UI_READY_DIALOG_MATCHUP_DEC_ID = "UI_READY_DIALOG_MATCHUP_DEC_";
const UI_READY_DIALOG_MATCHUP_DEC_LABEL_ID = "UI_READY_DIALOG_MATCHUP_DEC_LABEL_";
const UI_READY_DIALOG_MATCHUP_LABEL_ID = "UI_READY_DIALOG_MATCHUP_LABEL_";
const UI_READY_DIALOG_MATCHUP_INC_ID = "UI_READY_DIALOG_MATCHUP_INC_";
const UI_READY_DIALOG_MATCHUP_INC_LABEL_ID = "UI_READY_DIALOG_MATCHUP_INC_LABEL_";
const UI_READY_DIALOG_MINPLAYERS_DEC_ID = "UI_READY_DIALOG_MINPLAYERS_DEC_";
const UI_READY_DIALOG_MINPLAYERS_DEC_LABEL_ID = "UI_READY_DIALOG_MINPLAYERS_DEC_LABEL_";
const UI_READY_DIALOG_MINPLAYERS_INC_ID = "UI_READY_DIALOG_MINPLAYERS_INC_";
const UI_READY_DIALOG_MINPLAYERS_INC_LABEL_ID = "UI_READY_DIALOG_MINPLAYERS_INC_LABEL_";
const UI_READY_DIALOG_MATCHUP_MINPLAYERS_ID = "UI_READY_DIALOG_MATCHUP_MINPLAYERS_";
const UI_READY_DIALOG_MATCHUP_MINPLAYERS_TOTAL_ID = "UI_READY_DIALOG_MATCHUP_MINPLAYERS_TOTAL_";
const UI_READY_DIALOG_MAP_LABEL_ID = "UI_READY_DIALOG_MAP_LABEL_";
const UI_READY_DIALOG_MAP_VALUE_ID = "UI_READY_DIALOG_MAP_VALUE_";
const UI_READY_DIALOG_MODE_GAME_LABEL_ID = "UI_READY_DIALOG_MODE_GAME_LABEL_";
const UI_READY_DIALOG_MODE_GAME_DEC_ID = "UI_READY_DIALOG_MODE_GAME_DEC_";
const UI_READY_DIALOG_MODE_GAME_DEC_LABEL_ID = "UI_READY_DIALOG_MODE_GAME_DEC_LABEL_";
const UI_READY_DIALOG_MODE_GAME_VALUE_ID = "UI_READY_DIALOG_MODE_GAME_VALUE_";
const UI_READY_DIALOG_MODE_GAME_INC_ID = "UI_READY_DIALOG_MODE_GAME_INC_";
const UI_READY_DIALOG_MODE_GAME_INC_LABEL_ID = "UI_READY_DIALOG_MODE_GAME_INC_LABEL_";
const UI_READY_DIALOG_MODE_SETTINGS_LABEL_ID = "UI_READY_DIALOG_MODE_SETTINGS_LABEL_";
const UI_READY_DIALOG_MODE_SETTINGS_DEC_ID = "UI_READY_DIALOG_MODE_SETTINGS_DEC_";
const UI_READY_DIALOG_MODE_SETTINGS_DEC_LABEL_ID = "UI_READY_DIALOG_MODE_SETTINGS_DEC_LABEL_";
const UI_READY_DIALOG_MODE_SETTINGS_VALUE_ID = "UI_READY_DIALOG_MODE_SETTINGS_VALUE_";
const UI_READY_DIALOG_MODE_SETTINGS_INC_ID = "UI_READY_DIALOG_MODE_SETTINGS_INC_";
const UI_READY_DIALOG_MODE_SETTINGS_INC_LABEL_ID = "UI_READY_DIALOG_MODE_SETTINGS_INC_LABEL_";
const UI_READY_DIALOG_MODE_VEHICLES_T1_LABEL_ID = "UI_READY_DIALOG_MODE_VEHICLES_T1_LABEL_";
const UI_READY_DIALOG_MODE_VEHICLES_T1_DEC_ID = "UI_READY_DIALOG_MODE_VEHICLES_T1_DEC_";
const UI_READY_DIALOG_MODE_VEHICLES_T1_DEC_LABEL_ID = "UI_READY_DIALOG_MODE_VEHICLES_T1_DEC_LABEL_";
const UI_READY_DIALOG_MODE_VEHICLES_T1_VALUE_ID = "UI_READY_DIALOG_MODE_VEHICLES_T1_VALUE_";
const UI_READY_DIALOG_MODE_VEHICLES_T1_INC_ID = "UI_READY_DIALOG_MODE_VEHICLES_T1_INC_";
const UI_READY_DIALOG_MODE_VEHICLES_T1_INC_LABEL_ID = "UI_READY_DIALOG_MODE_VEHICLES_T1_INC_LABEL_";
const UI_READY_DIALOG_MODE_VEHICLES_T2_LABEL_ID = "UI_READY_DIALOG_MODE_VEHICLES_T2_LABEL_";
const UI_READY_DIALOG_MODE_VEHICLES_T2_DEC_ID = "UI_READY_DIALOG_MODE_VEHICLES_T2_DEC_";
const UI_READY_DIALOG_MODE_VEHICLES_T2_DEC_LABEL_ID = "UI_READY_DIALOG_MODE_VEHICLES_T2_DEC_LABEL_";
const UI_READY_DIALOG_MODE_VEHICLES_T2_VALUE_ID = "UI_READY_DIALOG_MODE_VEHICLES_T2_VALUE_";
const UI_READY_DIALOG_MODE_VEHICLES_T2_INC_ID = "UI_READY_DIALOG_MODE_VEHICLES_T2_INC_";
const UI_READY_DIALOG_MODE_VEHICLES_T2_INC_LABEL_ID = "UI_READY_DIALOG_MODE_VEHICLES_T2_INC_LABEL_";
const UI_READY_DIALOG_MODE_CONFIRM_ID = "UI_READY_DIALOG_MODE_CONFIRM_";
const UI_READY_DIALOG_MODE_CONFIRM_LABEL_ID = "UI_READY_DIALOG_MODE_CONFIRM_LABEL_";
const UI_READY_DIALOG_MODE_RESET_ID = "UI_READY_DIALOG_MODE_RESET_";
const UI_READY_DIALOG_MODE_RESET_LABEL_ID = "UI_READY_DIALOG_MODE_RESET_LABEL_";

// Admin/Tester UI - Widget ID bases (per-player IDs append viewer playerId).
const UI_TEST_HEADER_LABEL_ID = "UI_TEST_HEADER_LABEL_";
const UI_TEST_BUTTON_CLOCK_TIME_DEC_ID = "UI_TEST_BUTTON_CLOCK_TIME_DEC_";
const UI_TEST_BUTTON_CLOCK_TIME_INC_ID = "UI_TEST_BUTTON_CLOCK_TIME_INC_";
const UI_TEST_BUTTON_CLOCK_RESET_ID = "UI_TEST_BUTTON_CLOCK_RESET_";
const UI_TEST_BUTTON_MATCH_START_ID = "UI_TEST_BUTTON_MATCH_START_";
const UI_TEST_BUTTON_MATCH_END_ID = "UI_TEST_BUTTON_MATCH_END_";
const UI_TEST_BUTTON_POS_DEBUG_ID = "UI_TEST_BUTTON_POS_DEBUG_";
const UI_TEST_LABEL_CLOCK_TIME_ID = "UI_TEST_LABEL_CLOCK_TIME_";
const UI_TEST_PLUS_TEXT_ID = "UI_TEST_PLUS_TEXT_";
const UI_TEST_MINUS_TEXT_ID = "UI_TEST_MINUS_TEXT_";
const UI_TEST_RESET_TEXT_ID = "UI_TEST_RESET_TEXT_";
const UI_TEST_MATCH_START_TEXT_ID = "UI_TEST_MATCH_START_TEXT_";
const UI_TEST_MATCH_END_TEXT_ID = "UI_TEST_MATCH_END_TEXT_";
const UI_TEST_POS_DEBUG_TEXT_ID = "UI_TEST_POS_DEBUG_TEXT_";
const UI_ADMIN_MATCH_LENGTH_DEC_ID = "UI_ADMIN_MATCH_LENGTH_DEC_";
const UI_ADMIN_MATCH_LENGTH_INC_ID = "UI_ADMIN_MATCH_LENGTH_INC_";
const UI_ADMIN_MATCH_LENGTH_LABEL_ID = "UI_ADMIN_MATCH_LENGTH_LABEL_";

// Debug Positioning UI
const UI_POS_DEBUG_CONTAINER_ID = "UI_POS_DEBUG_CONTAINER_";
const UI_POS_DEBUG_X_ID = "UI_POS_DEBUG_X_";
const UI_POS_DEBUG_Y_ID = "UI_POS_DEBUG_Y_";
const UI_POS_DEBUG_Z_ID = "UI_POS_DEBUG_Z_";
const UI_POS_DEBUG_ROTY_ID = "UI_POS_DEBUG_ROTY_";

// Admin Panel (decoupled from main Ready Dialog)
const UI_ADMIN_PANEL_BUTTON_ID = "UI_ADMIN_PANEL_BUTTON_";
const UI_ADMIN_PANEL_BUTTON_LABEL_ID = "UI_ADMIN_PANEL_BUTTON_LABEL_";
const UI_ADMIN_PANEL_CONTAINER_ID = "UI_ADMIN_PANEL_CONTAINER_";

//#endregion -------------- String Variables --------------------
